### ISSUE TITLE
Mouse middle button click on link

### ISSUE THREAD

**Issue by Sential** [cefsharp/CefSharp#1021]
Hello, how to open links in new tab when the middle button was pressed?

**Comment by amaitland** [comment]
Please include additional information, have a read over the following as a guide.
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

**Comment by Sential** [comment]
I'm using WinForms in x86. I tried FocusHandler and Event on mouse click, but it didn't worked.

if (e.Button == Forms.MouseButtons.Middle){
//action...
}

**Comment by amaitland** [comment]
I'm not aware of any relevant hooks in the `CEF API`, so it may not be possible, or at least it might not be easy.

Without actually looking into the problem, I'd maybe look at hooking the `WndProc` and capture the middle mouse button, combine that with `OnBeforePopup` to cancel the popup creation and open a new browser instance yourself. 

@rassilon may have a better idea?

**Comment by Sential** [comment]
Thank you for answer :) I will try that :)

**Comment by rassilon** [comment]
Oh ick. You'd have to capture the correct HWND from CEF. That seems like just asking for trouble. It might be a bit easier if you were using WPF to be honest. That way, due to using offscreen rendering you could more easily intercept the middle button mouse clicks in a sensible way.

I'm not sure if there's a better way atm. When CefSharp exposes all of the HTML frames in a browser instance, then you could (re)install a JavaScript middle button mouse click handler at appropriate times if such a thing is possible.

The much simpler approach would be to examine options utilizing a context menu item, but that wouldn't be the middle mouse button any longer.

Bill

**Comment by Sential** [comment]
Thank you for answer.

**Comment by amaitland** [comment]
> Can you make event on mouse click in the next update?

When/if `CEF` exposes an `API` for mouse clicks then we can look at implementing something.

**Comment by Sential** [comment]
Oh, thanks. I'm waiting. :)

**Comment by jankurianski** [comment]
> Oh, thanks. I'm waiting. :)

Don't hold your breath, the following forum thread from *2012* indicates it is not important to the project, and besides, there are workarounds:
  http://www.magpcss.org/ceforum/viewtopic.php?f=10&t=1056

Unless you are the one to implement this and submit a patch to the CEF project to extend the CEF API, it is unlikely to occur.

You should switch to the `WPF` control as Bill recommended and intercept mouse clicks before they are sent to CEF.

**Comment by Shakras** [comment]
Don't know if it would be needed, but I found easy solution that helped me.
In IRequestHandler at OnOpenUrlFromTab check WindowOpenDisposition like this:
`if (targetDisposition == CefSharp.WindowOpenDisposition.NewBackgroundTab)
            {
                ==> Open 'targetUrl' on new tab here.
                return true;
            }`
