### ISSUE TITLE
Option to Disable navigation of link to target window and open in default browser 

### ISSUE THREAD

**Issue by bharatdwarkani** [cefsharp/CefSharp#1069]
Is there any property or an event to disable opening of link in target window for Hyper link ? When I click on a link to open it opens in an internal dialogue that dialogue lacks some functionality like link of source and other browser functionality so I would like to disable that and open a link in an default or other web browser available in system. One more reason to avoid opening in target window is when there is an hyper link which points to direct source of download file. It opens a blank dialogue and if IDownloadHandler is implemented it opens a blank and save as dialogue which is bit unusual.

Eg Content which reproduces this is Html content containing a link with target as opening Link

```  
private void webBrowser_IsBrowserInitializedChanged(object sender, DependencyPropertyChangedEventArgs e)

        {

            var link = @" <a href=http://www.anydirectlocation.zip target=" + "\"Opening Link\">Link</a>";
            webBrowser.LoadHtml(link, "http://example/");

        }

 ```

For WPF Platform

**Comment by rassilon** [comment]
There's a new `OnOpenURLFromTab` [RequestHandler method](https://bitbucket.org/chromiumembedded/cef/src/378a64b39aff1b50a8ad32fb04a235e3bd2d8729/include/cef_request_handler.h?at=master) in the CEF master branch now. 

I'm not sure if that will do what you want or not. You could try it out with CEF's cefclient if you like. CefSharp is still a ways away from moving to a version of CEF that includes this particular change since it is ONLY in master at the moment.

Bill

**Comment by amaitland** [comment]
I'd suggest starting with #600

You can easily deny opening the popup and pass the `Url` to another browser instance. Only downside is you loose the child parent relationship.

**Comment by bharatdwarkani** [comment]
@amaitland  Thanks provided solution works as expected.
