### ISSUE TITLE
New API Review

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#1073]
Work on the new `API` is fairly well progressed (thanks in large part to @rassilon). Everyone will soon have access to the underlying `CefBrowser`, `CefFrame` and `CefBrowser` host instances. Also previously hidden callbacks will now be available for `async` use.

Of particular note is the new `IPopupHandler` interface, which provides access to features that were previously routed directly into the `ChromiumWebBrowser` instance, most of which were ignored when the browser was a popup.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp/IPopupHandler.cs

You'll see that there are quite a few duplicate methods like `OnPreKeyEvent`, `OnKeyEvent`, `OnResourceRedirect`, `OnBeforeResourceLoad`, etc.

Is that confusing to have the duplicates? Would it be better to only expose the methods that are hidden?

@jankurianski @jornh @perlun @rassilon Any comments? Thoughts?

**Comment by jornh** [comment]
Sorry, haven't been able to look much at CefSharp lately, let alone use it. From your description above those additions sound great though :+1: Excellent work by you and @rassilon! 

> Everyone will soon have access to the underlying CefBrowser, CefFrame and CefBrowser host instances.

Can't wait to see what the dual `CefBrowser`s can do for me... couldn't  help it ... sure that's just a typo in there :smiling_imp:

I don't see having the duplicate methods in the `IPopupHandler` hurts anyone. Easier accessible and probably won't be that much of a maintenance burden - now that it's there. Do whatever you feel works best!

**Comment by jamespearce2006** [comment]
Could `IPopupHandler` derive from the interfaces where the duplicated methods reside? 

If there are methods that aren't needed in `IPopupHandler`, perhaps a set of base interfaces can be defined. For example, a base `IRequestResourceLoad`, containing the `OnBeforeResourceLoad` method. Then, both `IRequestHandler` and `IPopupHandler` can derive from this...

**Comment by amaitland** [comment]
> Sorry, haven't been able to look much at CefSharp lately, let alone use it.

No problem! How's things been? Hope all is well :smile: 

> Can't wait to see what the dual CefBrowsers can do for me... couldn't help it ... sure that's just a typo in there :smiling_imp:

lol :smile: It was supposed to say `CefBrowserHost`. Just a minor `typo`.

> Do whatever you feel works best!

It's one of those that sounds great in theory, now that I've seen it implemented, I'm not sure I like it. I think it's going to add confusion.

> Then, both IRequestHandler and IPopupHandler can derive from this...

I have considered that, though I'm not sure it's enough reason to balloon the number of interfaces out. There would need to be a number of interfaces that had only a one/two methods, which seems like a bit of a `code smell` and maintenance nightmare. Part of the reason that I'm rethinking the whole approach.

**Comment by rassilon** [comment]
> It's one of those that sounds great in theory, now that I've seen it implemented, I'm not sure I like it. I think it's going to add confusion.

I'm certainly not attached to the approach even though I did a bunch of the grunt work. I'm just not sure of an alternative approach that doesn't have people accidentally handling events for popup windows.

Bill

**Comment by amaitland** [comment]
> I'm just not sure of an alternative approach that doesn't have people accidentally handling events for popup windows.

Yep, I know. We then have the flip side where things like `IKeyboardHandler.OnPreKeyEvent` would previously have been triggered for popups. So we probably need to look at each method on a case by case basis?

Somewhere there is going to be an added complexity. A simply `browser.IsPopup` check on the client side is pretty easy in most cases. The question becomes, is there an easy way to convey that to the user? I'm sure many will welcome the additional flexibility.

Would be so much easier if we had a clean slate! All in favor of forking the project and abandoning `CefSharp`? lol

**Comment by rassilon** [comment]
If the method signatures were identical, it might not be too bad I think. (IPopupHandler that is).

> Would be so much easier if we had a clean slate! All in favor of forking the project and abandoning CefSharp? lol

Hah. Just you wait in a year or two we'll have Python Selenium unit tests dealing with CefSharp. :smile: 

Bill

**Comment by amaitland** [comment]
As you've probably seen I started to do that, and that's what sparked this post initially. As your well aware, once it's out there in the wild it's much harder to restructure the `API` later. 

https://github.com/amaitland/CefSharp/commit/4dbd6e36a7f68e81f90dce89e27f75e36f79d8c0

> Hah. Just you wait in a year or two we'll have Python Selenium unit tests dealing with CefSharp. :smile:

Why stop there? Let's get some `Perl` action happening! lol

http://search.cpan.org/~aivaturi/Selenium-Remote-Driver-0.15/lib/Selenium/Remote/Driver.pm

**Comment by amaitland** [comment]
Anyone have further comment on this? Ignoring the technical implementation detail for now. I'm interested in what people think makes for a useful `API`? What makes sense from a developer point of view?

**Comment by jankurianski** [comment]
The API looks really cool - simpler, more consistent and more powerful.  Quite a feat.

I tried upgrading my project to the API last night but got stuck on moving my code to the new `IResourceHandler` interface - the old handler had one callback that you fired after you had set the stream on the response object, so if you were handling calls asynchronously, it was obvious which response object was paired with the callback.

However now there are two methods:

```
bool ProcessRequestAsync(IRequest request, ICallback callback);
Stream GetResponse(IResponse response, out long responseLength, out string redirectUrl);
```

I am a bit confused about how I keep track of which request pairs up with which response?  In the examples, we only use this synchronously so we use a single `stream` class field, setting it in `ProcessRequestAsync` and then assume that `GetResponse` is fired immediately after `callback.Continue()` is fired.

I have the following situation in my app:
1. `ProcessRequestAsync` called with `http://myapp/AjaxLongPoll`.  I create a `Task` to return a response sometime later in step 4.
2. `ProcessRequestAsync` called with `http://myapp/image.png`.
3. I call `callback.Continue()` immediately for `http://myapp/image.png`
4. My task later calls `callback.Continue()` for `http://myapp/AjaxLongPoll`

I am not sure how my `Task` from step 1 is meant to create a `Stream` in step 4 and somehow communicate it back to `GetResponse`.  Any ideas?

------

I am a fan of re-using the existing handlers for the popup window events, and forcing the user to perform `browser.IsPopup` checks.  Less complexity and code duplication for us, and less hassle for the user.

If we do go ahead with this and remove `PopupHandler`, here are some ways we could educate users:
 - Block popups by default.
 - Add a `ChromiumWebBrowser.AllowPopups` boolean property with comment:

   "Set `AllowPopups` to true to allow popup windows to open.  You must choose one of these 2 options:
1. Allow CefSharp to create the popup windows for you, with an ugly caption bar.  This is what happens if you do nothing.  The popup window events are fired on your browser control handlers.  You WILL need to update your handlers such as `OnFrameLoadEnd` to check whether the events come from the popup - `browser.IsPopup` is true - or from your main browser control - `browser.IsPopup` is false.
2. Create your own popup windows/forms by setting the `LifeSpanHandler` property and creating a new `ChromiumWebBrowser` for the popup URL.  The popup browser events will be sent to your new `ChromiumWebBrowser` control."

 - In the `WinForms` and `WPF` example projects (not `OffScreen`), set `AllowPopups = true` and update all the handlers to check for `browser.IsPopup`.

**Comment by amaitland** [comment]
@jankurianski Awesome, thanks for the very detailed response! :+1: 

> However now there are two methods:

To unravel the mess that was `SchemeHandler` I've made the code a lot more like the underlying `CEF API`. As a result the `ResourceHandler` implementation changed as well. Basically each request will create a new `IResourceHandler` instance, so it's not so much about matching the calls up per say.

Using the following as a reference which will work in a `sync` fashion
https://github.com/cefsharp/CefSharp/blob/master/CefSharp/ResourceHandler.cs#L766

- Standard convention applies, to immediately cancel the request `return false`
- To handle the request in an async fashion spawn off a `Task` and return true.
- When the task has completed populate the local stream reference which you will use later in `GetResponse`
- Execute the callback
- Now `GetResponse` should be called
- Populate the `IResponse` object
- Return the `Stream`

We can likely provide an `abstract` `async` implementation that could hide some of the implementation detail. The new `API` isn't set in stone either, so if we can simplify or provide a cleaner implementation again then I'm all for that :+1: 

> I am a fan of re-using the existing handlers for the popup window events, and forcing the user to perform browser.IsPopup checks. Less complexity and code duplication for us, and less hassle for the user.

Exactly what I was looking for, a totally different perspective, thanks :+1: That would greatly simplify things under the hood, so it's worth considering :smile:

**Comment by jankurianski** [comment]
> Basically each request will create a new IResourceHandler instance, so it's not so much about matching the calls up per say.

Ah, that clears it up for me.  I had the wrong assumption that the same instance was re-used.  Cheers! :beers: 

> We can likely provide an abstract async implementation that could hide some of the implementation detail. The new API isn't set in stone either, so if we can simplify or provide a cleaner implementation again then I'm all for that

I see what you mean :+1:   I'll try to think about that as I do my integration using the current way.

**Comment by rassilon** [comment]
One of my previous bosses always recommended creating pits of success for your API (or indeed whatever you are actually producing) consumers.

i.e. Produce an API/whatever whose design makes it easy to succeed with, but more difficult to fail with.

The argument behind creating `IPopupHandler` in the first place isn't to make life easier for the authors of CefSharp. The argument is to make thinking about behavior not related to popups easier for consumers and to allow consumers more considered decisions (if they so choose) about when they want their handlers to be invoked with respect to popups. It may very well be that some consumers want the main handlers and the `IPopupHandler` handling methods to have the very same implementation,  From that perspective, it does indeed make sense to ensure that the signatures are the same. 

However, it still seems to me that a bunch of consumers will easily overlook the possibility of popups in their handler implementations. Short of authoring NDepend/FxCop/whatever checking rules for handlers to check if they've tested for `IsPopup` it seems to me that `IPopupHandler` helps remind API consumers of the detail they might otherwise accidentally overlook.

Thoughts?

Bill

**Comment by jankurianski** [comment]
Good points Bill.  The current design ensures that if a user is on auto-pilot, they don't get into trouble.  If they care about popups, they then need to handle it explicitly and this is made obvious via a separate interface.

My app disallows popups, so I'm not coming at this from a real need.  If I was to enable them, I wouldn't be happy with the default look and feel of CEF's popups, so I would probably create an owner `Form` with my app's standard decoration and have a dedicated `ChromiumWebBrowser` for the popup.  I would be happy with an all-or-nothing approach: either (a) accept the default popup behaviour (meaning CefSharp would not expose any popup-specific flag or interface), or (b) take over the popup entirely and put it in a new `ChromiumWebBrowser` in order to use the existing API.

**Comment by amaitland** [comment]
> One of my previous bosses always recommended creating pits of success for your API (or indeed whatever you are actually producing) consumers.

Sounds like a follower of `Ayende Rahien's` blog. (He's a big proponent of falling into the pit of success).

> However, it still seems to me that a bunch of consumers will easily overlook the possibility of popups in their handler implementations. Short of authoring NDepend/FxCop/whatever checking rules for handlers to check if they've tested for IsPopup it seems to me that IPopupHandler helps remind API consumers of the detail they might otherwise accidentally overlook.

For interfaces like `IKeyboardHandler` that make no differentiation between the main browser and popups we'll be subtly changing their behavior by suddenly only propagating the main browser events.

If we started from scratch would be take the same tact? I'd imagine we'd just wrap the bare `CEF API`. No other `CEF` based framework I've seen does anything different. And I'm not saying we can't be different, if there's a better way. I just want to make sure we have a clear direction going forward. It's quite apparent the existing `API` suffered from creep over the years, it should probably have been restructured when `CefSharp3` was introduced.

I'm quite happy to wipe the slate clean at this point and rewrite the `API` properly, regardless of history if the benefits are worth it long term. 

So what's the cleanest, easiest to use approach? What just makes sense?

**Comment by rassilon** [comment]
> Sounds like a follower of Ayende Rahien's blog. (He's a big proponent of falling into the pit of success).

Nah. The timelines don't seem to line up from what I can tell.

Here's a .Net blog quoting my old boss in a [blog](http://blogs.msdn.com/b/brada/archive/2003/10/02/50420.aspx).

> Backwards compatibility concerns:

Given how many other breaking changes we've made to the API one would hope they would read the release notes. :smile: 

> If I was to enable them, I wouldn't be happy with the default look and feel of CEF's popups, so I would probably create an owner Form with my app's standard decoration and have a dedicated ChromiumWebBrowser for the popup.

Well, funny you should mention that, because someone submitted a PR for WPF that creates  ChromiumWebBrowser controls (IIRC) for popups. There's no reason we couldn't do something similar, and not have a `IPopupHandler` interface.

Bill

**Comment by amaitland** [comment]
> Given how many other breaking changes we've made to the API one would hope they would read the release notes. :smile:

I'm not holding out hope on that one. It amazes me how quickly throw their hands in the air saying it's broken without reading even the most basic of documentation :frowning:
