### ISSUE TITLE
Multiple instance of Browser subprocess running taking considerable memory

### ISSUE THREAD

**Issue by bharatdwarkani** [cefsharp/CefSharp#1075]
I am facing issue in an application I am using 5-6 browsers and multiple sub process are running in Background taking memory. Also after continuous usage application slows down.

![image](https://cloud.githubusercontent.com/assets/12810605/8109568/6ec87d98-1025-11e5-829a-bb79533a8868.png)

**Comment by jornh** [comment]
The separate processes is not what I would call an issue - that's by design. :smile:  Both Chromium and CEF which CefSharp (and the commercial Google Chrome product) builds upon works the same way and spawns a separate OS process for each browser. It's just the name of the process that varies. For comparison here's some of my Chrome processes right now:
![windows task manager_2](https://cloud.githubusercontent.com/assets/766423/8111613/17a23336-1063-11e5-8c59-48b756d7685c.jpg)

With the "after continuous usage application slows down" you'd have to be more specific. See https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue for guidance on how to report good issues for CefSharp.

**Comment by amaitland** [comment]
The numbers your showing in the screenshot aren't particularly high, even if it was `10x` that I wouldn't be concerned either. Web browsers by nature are memory hogs.

> With the "after continuous usage application slows down" you'd have to be more specific.

The `Bug Report template` is an excellent place to start. Also what is your usage scenario? Can you provide a sample to reproduce the problem? Are you using `JavaScript` binding?

There's a new version coming, likely next week. `41.0.0` upgrade to `Chromium 41`, with it should be some performance improvements.

**Comment by amaitland** [comment]
New version is out. Any further update on this?
