### ISSUE TITLE
Copy command enabled without any content being copied

### ISSUE THREAD

**Issue by bharatdwarkani** [cefsharp/CefSharp#1086]
There is a CopyCommand  available in WPF browser. I have used that for context menu but that option is  enabled even if nothing is copied seems can execute returns true all the time.

**Comment by amaitland** [comment]
Version?

**Comment by amaitland** [comment]
Is the problem reproducible in the `CefSharp.Wpf.Example` project?

**Comment by bharatdwarkani** [comment]
Using CefSharp.Wpf -Version 39.0.2 . I am loading Html data from local source. 

Code I have used for enabling context menu
```

browser.ContextMenu = new System.Windows.Controls.ContextMenu();
            browser.ContextMenu.Items.Add(new MenuItem() { Header = "Select All", Command = browser.SelectAllCommand });
            browser.ContextMenu.Items.Add(new MenuItem() { Header = "Copy", Command = browser.CopyCommand });
            browser.ContextMenu.Items.Add(new MenuItem() { Header = "View Source", Command = browser.ViewSourceCommand });

```

**Comment by amaitland** [comment]
Code for `CopyCommand` is pretty straight forward. Just invokes `Copy()` on the `CefFrame` instance.
https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Wpf/ChromiumWebBrowser.cs#L1298

There doesn't appear to be any method to determine if text is selected
http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefFrame.html

It might be worth digging through the `cefclient` example to see if it demos a solution. Otherwise there probably isn't much we can do.

**Comment by amaitland** [comment]
If the `API` expands to support this or someone comes up with a clever idea we can reopen this issue.
