### ISSUE TITLE
cefsharp offscreen + winforms questions

### ISSUE THREAD

**Issue by edohy2y** [cefsharp/CefSharp#1129]
Hi Guys:

I am attempting to embed Chromium using cefsharp.
It is crashing without throwing any exceptions or logging any errors.

Flow:
user types in credential(proprietary winform app), clicks sign in.
start CefSharp.OffScreen.ChromiumWebBrowser go to login url and perform login.
Cef.Shutdown()
user browser through some grid data, double clicks on row
start CefSharp.WinForms.ChromiumWebBrowser to load respective page.

crashes on the following line:
var chromiumWebBrowser = new CefSharp.WinForms.ChromiumWebBrowser(url)
                {
                    Dock = DockStyle.Fill
                };

additional information:
CefSharp.WinForms.ChromiumWebBrowser is inside a Form class.  i.e. public particl class SomeForm:Form

Questions:
1. Why does it crash without any logs and didn't throw any errors.
2. Does OffScreen and Winform share the same cookie store(login tokens etc)?
3. Is there any way for me to get any meaningful reason about why it is crashing?
4. Can CefSharp.OffScreen and CefSharp.Winforms be used together under the same WinForm desk top app?

**Comment by amaitland** [comment]
You cannot shutdown and restart, it's a limitation of the framework.

**Comment by amaitland** [comment]
> Why does it crash without any logs and didn't throw any errors.

Basically because you'd already called `Shutdown`.

> Does OffScreen and Winform share the same cookie store(login tokens etc)?

Running within the same process, they'll share the same data store. Which by default is an in memory one. 

> Is there any way for me to get any meaningful reason about why it is crashing?

You can increase the `LogSeverity` to obtain additional information. A file called `debug.log` will be produced in your `bin `directory. (This is the default, you can of course change this through `CefSettings`)
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/CefExample.cs#L71

> Can CefSharp.OffScreen and CefSharp.Winforms be used together under the same WinForm desk top app?

Never tried it, though I see no technical reason why not. Just don't attempt to `Shutdown` and everything should play nicely.

**Comment by edohy2y** [comment]
Thanks, I will give it a try without the shutdown.
