### ISSUE TITLE
Set useragent in CefSettings stop working in versions up to 37.0.0.0

### ISSUE THREAD

**Issue by MoleDJ** [cefsharp/CefSharp#1153]
```
Cef.Initialize(new CefSettings()
{
	UserAgent = "Mozilla/5.0 (Linux; <Android Version>; <Build Tag etc.>) AppleWebKit/<WebKit Rev> (KHTML, like Gecko) Chrome/<Chrome Rev> Mobile Safari/<WebKit Rev>",
});
```

This only works on versions <= 37.0.0.0

**Comment by amaitland** [comment]
If you load `chrome://version/` what does it say? There should also be a command line argument `--user-agent`, check that that comes through.

**Comment by MoleDJ** [comment]
I have it embebed in a big project and is dificult for me to test that. I see that useragent not changed using fiddler

**Comment by amaitland** [comment]
Open up task manager, find the `BrowserSubProcess` that has `--type=renderer`, check there's a `user-agent` param

What does `Cef.Initialize` return? Need to make sure `Cef.Initialize` is called before the first instance of `ChromiumWebBrowser` is created, otherwise it will `Initialize` with a default set of settings and the values your using will be ignored. This behavior was changed in `39` and above.

There are example projects you can test with, e.g. https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by amaitland** [comment]
@MoleDJ Did you work out the problem?

**Comment by MoleDJ** [comment]
Sorry for the delay, yes, problem gone. The problem was I have and class that derive from chrmiumWebBroser and I did the cef.initialize in the constructor. That worked in <39. Now I moved the cef.initialize to my app.cs code, and now it works fine again. Thanks!, i close the issue.

**Comment by amaitland** [comment]
Great :+1: Next version will throw an exception if already initialized, so the behavior will be more explicit.
