### ISSUE TITLE
Cannot set rounded corners for ChromiumWebBrowser WPF control

### ISSUE THREAD

**Issue by DominikPalo** [cefsharp/CefSharp#1285]
I wrapped my ChromiumWebBrowser into a border with CornerRadius set, but browser still overflows the border (so doesn't have corners rounded)

```
    <Border CornerRadius="10">
            <cefSharp:ChromiumWebBrowser  Address="{Binding WebComponentUrl, Mode=TwoWay}" Width="700" Height="400"   WebBrowser="{Binding WebBrowser, Mode=OneWayToSource}" />
    </Border>
```

I'm also tried to set the OpacityMask for the ChromiumWebBrowser, but in this case browser view is not visible anymore. 

```
    <Border x:Name="mask" CornerRadius="14" Background="White">
            <cefSharp:ChromiumWebBrowser  Address="{Binding WebComponentUrl, Mode=TwoWay}" Width="700" Height="400"  WebBrowser="{Binding WebBrowser, Mode=OneWayToSource}">
                <cefSharp:ChromiumWebBrowser.OpacityMask>
                    <VisualBrush Visual="{Binding ElementName=mask}" />
                </cefSharp:ChromiumWebBrowser.OpacityMask>
            </cefSharp:ChromiumWebBrowser>
    </Border>
```

**Comment by amaitland** [comment]
> I wrapped my ChromiumWebBrowser into a border with CornerRadius set, but browser still overflows the border (so doesn't have corners rounded)

The control is actually rendered as an image, so you should be able to perform any transform you like to it. 

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Wpf/ChromiumWebBrowser.cs#L908

How does wrapping a static image in a `<Border/>` behave? It's been a while since I did more than tinker with `WPF`.

> I'm also tried to set the OpacityMask for the ChromiumWebBrowser, but in this case browser view is not visible anymore.

The `CefSharp.Wpf.Example` project demos setting the opacity.

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Wpf.Example/Views/BrowserTabView.xaml#L172

**Comment by amaitland** [comment]
See https://chriscavanagh.wordpress.com/2008/10/03/wpf-easy-rounded-corners-for-anything/
