### ISSUE TITLE
Key F11 don't work when canvas has been clicked

### ISSUE THREAD

**Issue by shirotzu** [cefsharp/CefSharp#1374]
when i set a event as detect the keydown or keypress F11 this work but if i clicked the canvas of a game HTML5 this not work.
how fix this?

Thanks in advance

**Comment by amaitland** [comment]
How does it behave in `Chrome`? How does it behave in `cefclient`?

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

Remember `CefSharp` has no control over the inner workings of the browser, so there's a lot of things that are outside the scope of this project and must be referred back upstream to `CEF`.

**Comment by amaitland** [comment]
Remember to include the version and flavor (`WinForms`, `WPF`, `OffScreen`) with every issue you create.

Providing an example that reproduces your problem is something you should also consider.

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue

**Comment by amaitland** [comment]
Closing due to lack of feedback from `OP`.
