### ISSUE TITLE
i think CefSharp.OffScreen.Example can not load some website.

### ISSUE THREAD

**Issue by coldicelion** [cefsharp/CefSharp#1430]
hi, i try to use OffScreen.Example to open a website to get screenshot, it was like something  stack with it, so i tried every CefSharp's version, but it looks like every CefSharp version has this same problems.please help me, thanks you guys a lot !

![image](https://cloud.githubusercontent.com/assets/6093582/11266755/d43e5eb4-8ee1-11e5-8ef2-49f7a1a5561a.png)

**Comment by amaitland** [comment]
> CefSharp's version, but it looks like every CefSharp version has this same problems.please help me, thanks you guys a lot !

The javascript is throwing some errors by the looks of it. Nothing `CefSharp` can do really.

**Comment by coldicelion** [comment]
thanks, can i set the cefsharp to ignore the javascript errors?

**Comment by amaitland** [comment]
> thanks, can i set the cefsharp to ignore the javascript errors?

It's only logged as an `Info` message, so it's likely not blocking because of the error, more likely the script failed to execute is causing the problem.

You can load `DevTools` with `ShowDevTools` (even in the `Offscreen` project) to see what's going on.

Also I'd try loading the website in the `WPF` or `WinForms` examples to see how it behaves normally.

**Comment by coldicelion** [comment]
^_^ thank you  very much!

**Comment by amaitland** [comment]
@coldicelion How'd you go? Any follow up on this?
