### ISSUE TITLE
Feature Request - Add IRequestHandler.GetResourceResponseFilter

### ISSUE THREAD

**Issue by patryksuchowierski** [cefsharp/CefSharp#1439]
How can I get every response's content? Obiously, creating RequestHandler and using OnResourceResponse method doesn't work. All you can see in there is response headers. Is there any other way I could accomplish that? Let's say I navigate to "google.com", while getting in there, browser sends multiple requests (depending on the pages javascript). How to get content of responses to those requests?

**Comment by amaitland** [comment]
> How to get content of responses to those requests?

Unfortunately the `CEF` framework doesn't expose such a feature out of the box. It's a known limitation.

http://magpcss.org/ceforum/viewtopic.php?f=6&t=13461

You can implement a workaround, for which there are two similar options, they're both a bit of a hack though.

You can implement a `Scheme` handler, register it for `http` and `https`, use some of the built in `.Net` class to download the file, populate the stream and execute the callback when it's complete. 

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/CefSharpSchemeHandler.cs#L51

If you only need specific file types, then you can likely make the implementation more efficient.

The other is to implement `IResourceHandlerFactory`, for both cases you end up implementing `IResourceHandler`. The example for `Scheme` handler is cleaner and more details, so that's what I've gone with. Technically both are similar. (They were refactored to use much of the same code).

**Comment by amaitland** [comment]
A new feature was added to `CEF` a couple of hours ago.

https://bitbucket.org/chromiumembedded/cef/commits/456ea5a

Once implemented this will likely become much easier.

**Comment by patryksuchowierski** [comment]
Thanks for the info, I'll look into it, however, I've already used gecko fx which allowed me to do that easily

**Comment by amaitland** [comment]
> I've already used gecko fx which allowed me to do that easily

No problem :+1:

**Comment by amaitland** [comment]
Look at exposing the raw data using an `unmanagedmemorystream` - likely the best performance though not necessarily the easier `API` to use.
https://msdn.microsoft.com/en-us/library/system.io.unmanagedmemorystream%28v=vs.110%29.aspx

**Comment by weituotian** [comment]
@amaitland 
so how to use it?
```
            CefSharp.WinForms.ChromiumWebBrowser wb = new CefSharp.WinForms.ChromiumWebBrowser("news.sina.com.cn");
            wb.Dock = DockStyle.Fill;
            wb.RequestHandler.GetResourceResponseFilter=new ??????????????
            this.Controls.Add(wb);
```
