### ISSUE TITLE
Find next/previous not working in PDF

### ISSUE THREAD

**Issue by Ilya-Onboard** [cefsharp/CefSharp#1584]
When a PDF is loaded into the winForms example, the search function only finds the first result. Next and previous buttons do not do anything.

**Comment by amaitland** [comment]
If you have a moment it would be very useful if you could help isolate the problem. We need to determine if the problem is in the `CefSharp` wrapper, or in the `CEF` project (for which `CefSharp` is based).

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

Can you confirm what version your using? e.g. `47.0.2`

**Comment by amaitland** [comment]
@Ilya-Onboard Any follow up on this?

**Comment by amaitland** [comment]
@Ilya-Onboard Please provide an update on this issue (It will be closed otherwise).
