### ISSUE TITLE
System.IO.FileNotFoundException when running samples

### ISSUE THREAD

**Issue by HoosierMike** [cefsharp/CefSharp#175]
Compiling and running it right out of the box in VS2012, no errors, but all apps crash with that eror

Problem signature:
  Problem Event Name:   CLR20r3
  Problem Signature 01: cefsharp.wpf.example.exe
  Problem Signature 02: 1.25.4.34284
  Problem Signature 03: 523ce228
  Problem Signature 04: CefSharp.Wpf.Example
  Problem Signature 05: 1.25.4.34284
  Problem Signature 06: 523ce228
  Problem Signature 07: 3
  Problem Signature 08: 1
  Problem Signature 09: System.IO.FileNotFoundException
  OS Version:   6.1.7601.2.1.0.256.48
  Locale ID:    1033
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

**Comment by charlau** [comment]
I’m having the same exact problem as dimzon, but with an app of my own (with CefSharp/WinForms). I’m using NuGet. Works fine in VS2015 community, but even on the same machine, I get the error with the published package.

Any help would be appreciated, thanks.

**Comment by amaitland** [comment]
See #1314

Any further questions please ask on [Gitter Chat](https://gitter.im/cefsharp/CefSharp#). Also prefer if you didn't comment on issues that have been inactive for a few years.

**Comment by charlau** [comment]
Thanks, solved my problem.

**Comment by dana-p** [comment]
Make sure you have the Visual C++ Redistributable Package for Visual Studio 2013 installed. https://www.microsoft.com/en-ca/download/details.aspx?id=40784

That's what worked for me, in the end.

**Comment by Wesley-Chan** [comment]
> Make sure you have the Visual C++ Redistributable Package for Visual Studio 2013 installed. https://www.microsoft.com/en-ca/download/details.aspx?id=40784
> 
> That's what worked for me, in the end.

I just verified this on a newly installed Windows 7 SP 1. Now that we have enough reports, can we, or should we at least put a warning on the [FAQ page](https://github.com/cefsharp/CefSharp/wiki/Output-files-description-table-\(Redistribution\)) to tell people who might be using old versions of CefSharp that installing the latest (2017) VCRedist isn't satisfying the prerequisites?

**Comment by perlun** [comment]
Thanks for the feedback @Wesley-Chan. Feel free to edit the FAQ page as you suggest, or discuss this further in the [Gitter chat](https://gitter.im/cefsharp/CefSharp#) if you feel unsure about how to write it.

I will lock this issue now from further comments, since there's too big risk that people will miss comments being written here (because the issue was closed a long time ago).

**Comment by amaitland** [comment]
There are many many references within that outline the `VC++` version requirements.

Here are some:
- https://github.com/cefsharp/CefSharp/wiki/Output-files-description-table-(Redistribution)#visual-c
- https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#Including_vcredist
- https://github.com/cefsharp/CefSharp#release-branches
- Every `Nuget` package since version `39` has a `Readme.txt` file which is opened when you install the `Nuget packages`, it lists the requirements for the version you have installed. https://github.com/cefsharp/CefSharp/blob/cefsharp/39/NuGet/Readme.txt#L18
https://github.com/cefsharp/CefSharp/blob/cefsharp/71/NuGet/Readme.txt#L31

The original issue here appears to be that of users compiling the project from source with `Debug` selected, which will only run on machines with `Visual Studio` installed. If you are compiling from source you must build in `Release` mode to run on a machine **without** `Visual Studio` installed.
