### ISSUE TITLE
The error "A breakpoint has been reached" coming although largeaddressaware attribute already set for the subprocess.

### ISSUE THREAD

**Issue by rajeevshuklaciti** [cefsharp/CefSharp#1768]
The error "A breakpoint has been reached" is still coming for me although i had already set largeaddressaware attribute as per given instruction described in https://github.com/cefsharp/CefSharp/commit/67e34d2fcd6a3d0e109e03c2d8dcef3f585cb6e9.

Its not a consistently reproducible issue for me but it is occurring many times in Production.

Could you please help me on this?
Many thanks in advance.

**Comment by amaitland** [comment]
@rajeevshuklaciti I find it very strange you posted on here and `CefGlue` issue tracker.  

Follow the suggestions outlined at https://bitbucket.org/xilium/xilium.cefglue/issues/145/the-error-a-breakpoint-has-been-reached#comment-29808199

**Comment by JosefNemec** [comment]
Sorry to bring up this old issue, but some of my users are getting "A breakpoint has been reached" error after application is running for a long time and I'm suspecting CEF as being one of the possible causes. Do you have archive of suggestions from that cefglue issue link? It's no longer available, sadly.

**Comment by amaitland** [comment]
Please open an issue on https://github.com/cefsharp/Questions-and-Support/issues making sure to fill out the question template https://github.com/cefsharp/Questions-and-Support/blob/master/.github/ISSUE_TEMPLATE/question-template.md

**Comment by JosefNemec** [comment]
I don't want to open an issue and waste your time before I'm sure it's an issue in cefsharp, that's why I was asking if you have suggestions from the cefglue page you linked backed up somewhere. It's really weird issue that's hard to diagnose since I'm unable to reproduce it myself and it happens to my users only after the app is running for couple days straight without interruption.

I'll open an issue once I'm sure it's an issue in cefsharp, thanks for now.

**Comment by amaitland** [comment]
It's most likely you are hitting a breakpoint in Chromium,  possible out of memory.

> that's why I was asking if you have suggestions from the cefglue page you linked backed up somewhere

This issue was created four years ago, I don't remember any of the details. 

Open an issue in https://github.com/cefsharp/Questions-and-Support/issues, fill out th e template,  that'll give me at least some background information.

**Comment by Anoud95** [comment]
@JosefNemec  Hello can you please tell me how did you fix this issue ?
