### ISSUE TITLE
Project Status Update

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#1841]
Thanks to everyone who's contributed to the project :+1: My frustrations levels dealing with people have reached new heights and as a result I'm taking a step back from the project. At this stage I'll likely release a 55.0.0 early next year. I won't however be answering day to day questions or providing support. If anyone is interested in taking over development of the project then please say so. 

Unless your planning on contributing to the project no further comment is required on this subject.

**Comment by GrabzIt** [comment]
I hope you do consider coming back, as I really appreciate the regular releases. If you would start something like a [pateron](https://www.patreon.com/) account, I would give regularly to support cefsharps development.

**Comment by amaitland** [comment]
> If you want to start something like a pateron account, I would give regularly to support cefsharps development.

Thank you for the interesting suggestion. If I decide to go down that path I'll let you know.

**Comment by cztomczak** [comment]
Do what you like and do it mainly for yourself - it's a good recipe for frustrations to go away. Don't count on gratitude from people. If you like to write some code and fix a bug, do it. If the bug is frustrating and you don't really need to have it fixed, don't do it. If you like to answer a question do it. It is user's job to do some research before asking a question or reporting a problem. If they don't put an effort why should you. Just point them into the right direction, keep answers short and concise. Ignore toxic people because their frustrations will carry on to you. On the CEF Forum you can add Foes to ignore list in Control Panel, don't know about gitter ;) On github you can block users, but that's too harsh, more than just ignore. It's a huge project you're doing here, with so many users and issues, it requires lots of patience I guess :D

**Comment by amaitland** [comment]
> Don't count on gratitude from people

@cztomczak Hopefully the `cefpython` users are more appreciative! I've seen the amount of hard work you've put in and it's a fantastic effort 👍 

As for me the company I work for stopped active development on the project that used `CefSharp` over 18 months ago, so I no longer have a reason to continue development. 

> It's a huge project you're doing here, with so many users and issues, it requires lots of patience I guess :D

Your points above are all valid. I may come back to this at some point, for now I've simply had enough 😦

**Comment by amaitland** [comment]
As #1893 was successful for now I'll continue with a sponsorship model.
