### ISSUE TITLE
CefSharp runnable in Class Library?

### ISSUE THREAD

**Issue by mufoxe** [cefsharp/CefSharp#199]
Hi,

Is it possible to run CefSharp in a headless state say in a console app to download HTML and execute the received Javascript?

I'm looking at the BrowserCore, but it never seems to trigger the PropertyChanged event which makes sense as it's running outside the regular WinForms event loop.

Can I get it going somehow?

**Comment by s34nvideos** [comment]
Hi,

I visited the chat yesterday, and I was advised this is actually possible now. Can you confirm?

For clarify, I would need to run the control inside a class library, which offers browsing headers and javascript rendering like the WinForms example

**Comment by perlun** [comment]
There is an OffScreen package now, yes: https://www.nuget.org/packages/CefSharp.OffScreen/

I assume it works, here, you can read a bit more about it: https://github.com/cefsharp/CefSharp/wiki/General-Usage#offscreen-rendering-osr (I haven't written this part of the code myself, so I don't know much about it.)

I will lock this issue from further talk now, since ongoing discussions in closed issues/PRs are very hard to locate and notice for other people looking around. If you find specific issues with the OffScreen package though, please don't hesitate to ask on Gitter or open a new GitHub issue for that matter!
