### ISSUE TITLE
Web browser reloads on ActivateItem

### ISSUE THREAD

**Issue by magedassad** [cefsharp/CefSharp#2014]
Hello all, 

I have a wpf Caliburn Micro project with Chromium browser running on version 55.0.0 nuget package along with x86.

My project has menu buttons on top where the main page uses ActivateItem to switch between pages with IoC. One of the pages has the chromium browser. 

My issue is that when I use the browser to look up Google maps or do anything else on the browser then switch to any other page and return to the browser page everything gets reset and starts from the beginning.
I would like to keep the same state of the page where I left off, is that possible with what I'm currently doing?

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

**Comment by amaitland** [comment]
As a reference, what your seeing is likely similar to http://stackoverflow.com/questions/2238072/tabcontrol-disposes-of-controls-on-inactive-tabs

What your seeing is likely the default behavior of whatever `WPF` control your using. In this case, it's best to ask your question on `Stackoverflow`. Make sure you provide some sample code, otherwise people will just be guessing as to which controls your actually using. (Maybe the `Caliburn` people can help you also).
