### ISSUE TITLE
how to get json response content?

### ISSUE THREAD

**Issue by weituotian** [cefsharp/CefSharp#2032]
a page have some ajax json request, how to read these json response?

is it possiable?

i think it is a basic function to implement!

there is no example to do that! i even don not konw how to get started

**Comment by itshaadi** [comment]
@weituotian you want to send a request and then read the result which is in json format. is that what you meant?
for this type of action you can use **[axios](https://github.com/mzabriskie/axios)** to send and receive API requests from browser.
but you can also send and receive data from C# using **[jsonfx](https://github.com/jsonfx/jsonfx)** or **[ServiceStack.Text](https://www.nuget.org/packages/ServiceStack.Text)** i don't see why this issue is related to CEFSharp !?

**Comment by weituotian** [comment]
@itshaadi 
for example
i use cefsharp to load the [http://www.bilibili.com/video/av10118674/](http://www.bilibili.com/video/av10118674/)

it has a xhr request, which named playurl?
![image](https://cloud.githubusercontent.com/assets/7270968/25511834/14af506c-2bfc-11e7-8692-c58659c643f4.png)

the response is json like 

so how can i get the json format content ?

does cefsharp provide some api to do that?

**Comment by merceyz** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

**Comment by merceyz** [comment]
A quick google search gave me this:
http://stackoverflow.com/a/43652932/2923845

**Comment by weituotian** [comment]
@merceyz 
does it work?
