### ISSUE TITLE
Cefsharp deployment on non developer machine.

### ISSUE THREAD

**Issue by pnfarkya** [cefsharp/CefSharp#2112]
Hello , 
We are using wpf cefsharp 57.0.0 as a Chromium web control in our project , this is working fine when we are running this locally with visual studio but not working on others client machine where application is installed .
the problem we found out is , when we are deploying our application few files are not getting deployed which requires to run like  .pak , .dat and ChromiumWeBroswer.exe.
we want to package these files and install it in each client machine.
please help me out .

**Comment by avspeed** [comment]
so why don't you package them and install them on your client machine ?
Please refer to this for the list of required files
https://github.com/cefsharp/CefSharp/wiki/Output-files-description-table-%28Redistribution%29

**Comment by pnfarkya** [comment]
So do we need to build a MSI to install it if yes than what bill the location to install it in program files.

**Comment by avspeed** [comment]
That is correct. You can build an msi and bundle the rwquired files along with your executables. All required files need to be in the folder where your executable runs from

**Comment by merceyz** [comment]
You need to ship all required files yourself

**Comment by TehWardy** [comment]
This isn't helpful ... I copied my build output to another machine which literally contains everything as described above ... it still doesn't work.
Some guidance on this would be much appreciated.

**Comment by avspeed** [comment]
@TehWardy what about the appropriate vc++ runtime ? Is that installed on the machine where things are not working ?

**Comment by TehWardy** [comment]
Yup ... i did notice though that if I set everything up as described in the many youtube vids showing how to import, hack the proj file, add config element ect then combined that with a post build event I found on stack overflow that I was able to get it all working as an x86 build only ... switching to x64 doesn't work.

TBH ... it would be better if just like other "complex packages" ... take something like Entity Framework for example ... that comes with a powershell script that executes on import (or used to, EF core seems a lot better).

I think the issue is that instead of just consuming the C++ assemblies by pinvoke the setup seems to be dependent on actually executing chrome processes in the background then communicates with it ... is this a limit of the chrome architecture that it can't just run inproc on another thread group or something?

**Comment by SalmaTofaily** [comment]
Regarding VC++ dependency, my app worked without it. Any idea? is it really needed!?

I uninstalled VC++ from my machine, and also I removed any local deployment of them from the project, but my wpf cef-based app worked normally. Can this cause run time errors on specific clients machines, or is it related to specific functionalities?

**Comment by amaitland** [comment]
VC++ is mandatory, the CefSharp.Core.dll and CefSharp.BrowserSubProcess.Core.dll are both mixed mode C++/CLI dlls (require the VC++ runtime) and won't load without the runtime installed or bin deployed with your app.

If the browser loads successfully then the dlls that make up the VC++ runtime must be somewhere on the target machine. The browser will not load if the runtime is unavailable.
