### ISSUE TITLE
Feature Request- Print Margin Setting Option

### ISSUE THREAD

**Issue by adilmatech** [cefsharp/CefSharp#2138]
I have searched everywhere and also putted this question on stackoverflow. Actually I want to change print margin of widnows.print(). right now its printing but it is using default margin and it is very wide in my situation so I need to change the print margin like there is a option of printersettings in printtopdf.

**Comment by adilmatech** [comment]
Any one know this functionality is already available or it is actually a feature request?

**Comment by perlun** [comment]
This is unfortunately not so easy to implement at the moment, since it depends on functionality not yet available in CEF: https://bitbucket.org/chromiumembedded/cef/issues/1283/adding-print-options-to-cef3

Will close for now; please open a new issue if/when this lands in CEF. You can then submit a PR to CefSharp to have it implemented, if you have a chance. (I think this is a typical example of a "low prio" thing that is unlikely to be implemented unless someone who specifically needs it is willing to either do the work, or hire someone to do the work for them. It feels like a bit of a "corner case" in terms of CefSharp core functionality.)
