### ISSUE TITLE
DevTools dosen't work with popup window

### ISSUE THREAD

**Issue by JuliuszElsner** [cefsharp/CefSharp#2145]
- **What version of the product are you using?**
    -  57.0.0 from NuGet
- **What architecture x86 or x64?**
    - x86
- **On what operating system?**
    - Win7
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WPF
- **What steps will reproduce the problem?**
    - Implement ILifeSpanHandler using experimental code provided here : https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf.Example/Handlers/LifespanHandler.cs .
    - Implement KeyDown event (which calls ShowDevTools() on sender) for popup browser, so on some key you'll be able to open devtools. eg.
        ```c#
        private void PopupWindowKeyDown(object a_sender, KeyEventArgs a_event_args)
        {
            if (a_event_args.Key == Key.F12)
            {
                var popup_window = a_sender as IWebBrowser;
                popup_window.ShowDevTools();
            }
        }
        ```
    - Within WPF app open some popup window.
    - Open devtools by clicking button programmed in previous steps.

- **What is the expected output? What do you see instead?**
    - Expected is to see devtools window coresponding with popup window content. 
    - Instead of that displayed is duplicate of popup window with the same content but with Title on app bar "Dev tools".

- **Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)**
     - No

- **Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?**
    - As above.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
   - Hard to say because it's specific for provided implementation of creating popups.

**Comment by jankurianski** [comment]
Thanks for the bug report.  Because this is related to experimental code in an example file and you are extending the code yourself, you'll have to debug this issue.

It would be a benefit if you could publish your modified code as a fork or a Gist, as the problem could be related to how you implement the KeyDown event.

You could also set a breakpoint at https://github.com/cefsharp/CefSharp/blob/9801cc55fcd53a327d87e8007ff676ed7a919d91/CefSharp.Core/Internals/CefBrowserHostWrapper.cpp#L136 and see if `_browserHost` is correct (is it the popup browser, or is it the main browser)?

**Comment by perlun** [comment]
No feedback received for two months, closing. @JuliuszElsner, please ping back if you need more help in debugging this.
