### ISSUE TITLE
nuget version out of date

### ISSUE THREAD

**Issue by mihailik** [cefsharp/CefSharp#2158]
Currently CefSharp packages in nuget are 6 month old, and 4 major version out of date with the official Chrome.

https://www.nuget.org/packages/CefSharp.WPF/
https://www.nuget.org/packages/CefSharp.Common/

Version | Downloads | Last updated
-- | -- | --
57.0.0 (current version) | 54,814 | 6 months ago
55.0.0 | 34,954 | 8 months ago
53.0.1 | 11,751 | 10 months ago
53.0.0 | 39,732 | 10/10/2016
51.0.0 | 34,789 | 7/14/2016

In practice that means several major features are missing or incomplete: CSS Grid, FlexBox etc. Is there a roadmap to CEF/version update please?

**Comment by mihailik** [comment]
Particular interest in upgrading to Chrome v60+ is its headless mode.

As people start migrating their HTML automated tests on top of libraries integrating with headless, like <a href="https://github.com/GoogleChrome/puppeteer/">puppeteer</a>, we'd rather our <b>test</b> environment reflected the actual <b>runtime</b> environment.

With CEF still running on Chrome v57, tests running on headless Chrome will lag quite behind and may produce incorrect results.

**Comment by merceyz** [comment]
#1203 Is currently preventing a release of newer version(s)

**Comment by psmulovics** [comment]
We have a POC that works, but will take quite a while to get it released

**Comment by perlun** [comment]
@mihailik Please keep in mind that CefSharp is maintained by a group of volunteers and individuals. There is no large company backing this project.

Trust us: if it would just be a matter of "pressing a button", CefSharp 60.0.0 and 62.0.0 would already have been out. But this is not the case. It takes a lot of hard work. Some of it has been done in #2203 now; the road map can be found in #2200.

(Side note: Electron is still on Chromium 58, _even though_ it is backed by a large company - GitHub. So, if they still haven't been able to upgrade their code base, it's not realistic to expect CefSharp to go faster than them.)

I will close this now, since #2200 tracks the upgrade work. Let's continue the discussion there if needed.
