### ISSUE TITLE
Bound object, properties not mapped

### ISSUE THREAD

**Issue by valentin-turcu** [cefsharp/CefSharp#2161]
- **What version of the product are you using?**
    Nuget CefSharp 57.0.0

- **What architecture x86 or x64?**
    - Tested on both (x86 and x64)

- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
   - Winforms

- **What steps will reproduce the problem?**
Open MinimalExample project (Winforms), add the following class:

      public class TestClass
      {
           public string TestProp { get; } = "Test Prop";

           public string TestMethod()
           {
               return TestProp;
           }
        }

Register it in the BrowserForm constructor: 

   `browser.RegisterAsyncJsObject("bound", new TestClass(), BindingOptions.DefaultBinder);`

Add the debug port to CefSettings:

    `RemoteDebuggingPort = 9999`

Run the project, open debug console, type window.bound and see that it has only the method, not the property.
    
![ss_js](https://user-images.githubusercontent.com/6671776/31398309-d2365784-ade8-11e7-9003-48408e4a191e.png)

- **What is the expected output? What do you see instead?**
    Expected: properties being available in the bound object in the javascript context.

Am I missing anything here? I've read the General Usage, the FAQ and looked through the issue list, but everything indicates this should work out of the box, as described in the steps above.

**Comment by ray007** [comment]
How did you expect an asynchronous property to look like?
Not sure about the (deprecated) sync version, but here you'll need to make a method returning the value.

**Comment by valentin-turcu** [comment]
Since the concept of async/sync doesn't really apply for properties, I would've expected uniform behaviour across both the sync and async register methods regarding them.
In the (deprecated) sync version, you could do window.bound.object.property etc.

However if that's not the case, I must've misinterpreted the General Usage section on using the async bound object.

**Comment by cefsharp-ms** [comment]
The async bindings are using CEF IPC instead of WCF to avoid issues with the latter. However CEF doesn't have sync Chromium IPC exposed for performance reasons, this means that it's not possible to implement anything using this solution that requires blocking the render thread in the subprocess. This is the reason there are no property bindings in the async version and also I think it should be considered as a good practice not blocking your render thread, I'd suggest using get/set methods.
This said, if you really really have to do this, you could implement your own solution using sync XMLHttpRequests and a custom scheme handler.

**Comment by valentin-turcu** [comment]
All right, that makes it clearer why they're not implemented. I'll just switch to get/set methods in that case. 
Thanks and I am closing this.

**Comment by mcdevjin** [comment]
this not  support a filed but property !
