### ISSUE TITLE
Background color/image if it's empty

### ISSUE THREAD

**Issue by mamayadesu** [cefsharp/CefSharp#2196]
How to set background color or image if page hasn't own?
I tried `browser.BackColor = System.Drawing.Color.Blue;`, but it works only when page is loading. When it's loaded, background is white.

**Comment by perlun** [comment]
I think your best would be:

- Use the WPF control (not the Windows Forms.)
- Set the background color of the `UserControl` in which you are using the `ChromiumWebBrowser` to e.g. `Pink`.
- Let the web page be truly transparent, i.e. _do not set_ a background color.

The web page should now be shown on a Pink background. An example of this in action can be seen in the CefSharp.Wpf.Example:

![image](https://user-images.githubusercontent.com/630613/33501688-223301ee-d6e6-11e7-8121-208ea06b123f.png)

I will close this issue now, since this is not really an _issue_ per se, more a question on how to use CefSharp. If you have further questions, please ask in the [Gitter Chat](https://gitter.im/cefsharp/CefSharp) since more people are able to help you there.
