### ISSUE TITLE
I printed pdfdocument, the top content is truncated

### ISSUE THREAD

**Issue by stonezhu870** [cefsharp/CefSharp#2215]
### Bug Report
- What version of the product are you using?**
- 49.0.1.0
- x86 
- Win7
-  `WPF`

I use wpf，the chromiumWebBrowser show a pdf file. I use chromiumWebBrowser.Print() to print the pdf content,The vast majority of pdfs are printable, but if part of the content is particularly close to the edge of the page, the printed edge of the content is truncated。

preview screenshots image:
![image](https://user-images.githubusercontent.com/3832691/34200990-0960835e-e5ae-11e7-9738-acc6b1038ff9.png)

printed screenshots image:
![image](https://user-images.githubusercontent.com/3832691/34201503-a4f07f1c-e5af-11e7-8bd4-6bb175dcfc18.png)

pls help me, thx.

**Comment by jankurianski** [comment]
This is most likely a CEF problem.  CefSharp is a wrapper around CEF.

However, the version you are using is old and is no longer supported.  Most likely this issue is fixed in newer versions.  Please upgrade to CefSharp 57 or newer and try again.

Once you have upgraded, if the problem still exists, please follow instructions here under section "Does this problem also occur in the CEF Sample Application from ...": https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by stonezhu870** [comment]
Because I will support Xp, so I used cefsharp version 49. 
However, I tested cefsharp57, the printed document is the same, the content is truncated

**Comment by jankurianski** [comment]
What about using `cefclient` with the off-screen-rendering parameters?

**Comment by stonezhu870** [comment]
I used settings.EnableInternalPdfViewerOffScreen(), means enabled

**Comment by amaitland** [comment]
If the problem can be reproduced in the latest version (at time of writing ` CEF 3.3239.1706.gcd33baa`) then an issue should be created on https://bitbucket.org/chromiumembedded/cef/overview with a list of steps to reproduce the problem (and post a link to the issue here for reference).

As printing is completely in the control of `CEF` upgrading to a newer version is the only option in my opinion. The `62.0.0-pre0` packages are on `Nuget.org`, you can use those for testing.

There are no support options for `Windows XP` from a `Chromium/CEF/CefSharp` point of view, might be worth you checking out `GeckoFX`
