### ISSUE TITLE
Create Snapshot using Bitblt

### ISSUE THREAD

**Issue by Ratcha9** [cefsharp/CefSharp#2286]
- **What version of the product are you using?**
Nuget Package 63.0.1

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Windows10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms component in WPF application

- **What steps will reproduce the problem?**
I've pushed an example to [MinimalExample](https://github.com/Ratcha9/CefSharp.MinimalExample). There I've modified the WPF proj:
- Removed WPF CefSharp Browser
- Winforms CefSharp browser added
- Button added on top

A click on the button creates a Bitmap with the recommended [gist](https://gist.github.com/jankurianski/f3419d4580517516c24b) and shows the image in a new window.
Since the update to version 63.0.1 I am getting a black image. With version 57.0 it is working fine

- **What is the expected output? What do you see instead?**
Expectation: screenshot of the browser content
Actual result: black bitmap

- **Please provide any additional information below.**
In my real wpf application I am using Bitblt and PrintWindow. In order to mitigate the airspace issue, while we are showing e.g. modal dialogs "above" the browser, we hide the winforms hwnd, take pictures of it with PrintWindow and render that bitmap in WPF. This hacky workaround was pretty useful, since it worked with about 7-30 fps. I can reimplement this in the example, if it would help

**Comment by Ratcha9** [comment]
Hi, thank you for your reply. Sorry, I am not aware whether bitblt works in pure winforms application. Unfortunately neither the bitblt nor the printwindow approach work with the new version. I can add the implementation to the minimal example in the next days

**Comment by Ratcha9** [comment]
so, I've added a basic implementation for using printwindow in my example fork. 
@jankurianski when do you think you could check this?

**Comment by amaitland** [comment]
Nothing has really changed from a `CefSharp` point of view. `BitBlt` wasn't something that was explicitly supported, it just happened to work. It would be helpful to test in just a pure `WinForms` app to see if it's entirely broken, or just within the context of `WPF`.

Have a look at the `Chrome issue` tracker, 
https://bugs.chromium.org/p/chromium/issues/list?can=1&q=bitblt&sort=-modified&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified
https://bugs.chromium.org/p/chromium/issues/detail?id=633283&can=1&q=bitblt&sort=-modified&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

> In my real wpf application I am using Bitblt and PrintWindow. In order to mitigate the airspace issue, while we are showing e.g. modal dialogs "above" the browser, we hide the winforms hwnd, take pictures of it with PrintWindow and render that bitmap in WPF. This hacky workaround was pretty useful, since it worked with about 7-30 fps. I can reimplement this in the example, if it would help

Is there a reason your not using the `WPF` version? (Or even the `Offscreen` version if you want total control).

**Comment by Ratcha9** [comment]
Thank you for your reply.
I use webgl content in the browser with user interaction like panning or zooming with the mouse. The Winforms version is as fast as native in chrome. The wpf version is significantly slower and does not feel smooth.

**Comment by amaitland** [comment]
The WPF version is much faster now, thought still a way off being on par with the WinForms version, you will in most cases on modest hardware get better than 7fps. 30fps is very achievable. 

From a CefSharp point of view I don't think there are a lot of options, others are reporting similar problems when interfacing directly with Chrome. 

I'll leave this open for you to discuss for a while though I suspect it'll be closed as upstream as it's outside of our control.

**Comment by 803617** [comment]
Have the same problem after update 57->63 in WinForms application. Snapshot per BitBlt with version 57 works fine, with version 63 black.

**Comment by chylex** [comment]
In general, the only time I remember black screens is when the window or control isn't visible (as you describe with `hide the winforms hwnd`), but that shouldn't have changed since 57, i.e. if that's your issue then I don't know why it worked before in the first place.

@803617 Would be helpful if you showed your code, I've been using `BitBlt` on a Form with a browser in it for a while and haven't noticed any issues when updating to 63 or newer.

**Comment by Ratcha9** [comment]
@chylex Well , BitBlt isn't working either when the form is visible :(
@amaitland Thanks for your reply, but the wpf version is really far away from the performance of the winforms version

**Comment by 803617** [comment]
My test project creates this black snapshot for me.
[TestCefSharp.zip](https://github.com/cefsharp/CefSharp/files/1793941/TestCefSharp.zip)

**Comment by chylex** [comment]
Here's my WinForms code, maybe it'll help. I'm calling it with the Form handle, the Form is visible but outside all monitors, if you need to simulate invisible forms.
https://github.com/chylex/TweetDuck/blob/64977964e8e8c7bc4c419a0babbc37bfa7de92c7/Core/Utils/NativeMethods.cs#L133-L143
https://github.com/chylex/TweetDuck/blob/07af99f862d6e0f44ab352dbf86d71c0541452a4/Core/Notification/Screenshot/FormNotificationScreenshotable.cs#L48-L65

**Comment by Ratcha9** [comment]
@chylex Thank you for sharing your code. That's exactly the same code I am using. Do you set any specific cef settings or any cmd line args for cef? Could you share them?

**Comment by chylex** [comment]
Nothing that should affect BitBlt, afaik. I'm on CefSharp 64.0.0-CI2508 with legacy JS binding, so it should be consistent with previous versions. The code has been working since 55, and only had minor changes (like screenshoting window border, which was then removed when I decided to move the screenshotted Form outside all monitors where borders aren't rendered).

**Comment by Ratcha9** [comment]
BitBlt works, if I disable the gpu of course. I'm wondering if there are any other cmd line args you are using @chylex ?

**Comment by chylex** [comment]
By default, only `disable-pdf-extension=1, disable-plugins-discovery=1, enable-system-flash=0`. GPU is enabled.

**Comment by Ratcha9** [comment]
Unfortunately those args did not change anything. I did some research and I've found a PR on bitbucket for CEF: https://bitbucket.org/chromiumembedded/cef/pull-requests/96/osr-fix-gpu-cpu-readback-performance/diff
By trial and error I've found out that the arg use-angle helped without any performance decrease.
`settings.CefCommandLineArgs.Add("use-angle", "gl");` 

I am not aware of any side effects by using this argument.
@amaitland do you have any concerns?

**Comment by Ratcha9** [comment]
Description for use-angle switch: 

Select which ANGLE backend to use. Options are: default: Attempts several ANGLE renderers until one successfully initializes, varying ES support by platform. d3d9: Legacy D3D9 renderer, ES2 only. d3d11: D3D11 renderer, ES2 and ES3. warp: D3D11 renderer using software rasterization, ES2 and ES3. gl: Desktop GL renderer, ES2 and ES3. gles: GLES renderer, ES2 and ES3.

**Comment by Ratcha9** [comment]
use-angle did not work on different environments. Especially with intel HD graphiccards BitBlt did not work. We tested the following settings and until now it is working like a charm:
`settings.CefCommandLineArgs.Add("in-process-gpu", "1");`
`settings.CefCommandLineArgs.Add("enable-gpu", "1");`
`settings.CefCommandLineArgs.Add("enable-begin-frame-scheduling", "1");`
Does anyone have any concerns using these switches?

**Comment by amaitland** [comment]
@Ratcha9 Thanks for posting your workaround 👍 

> Restricted by its sandbox, the Renderer process (which contains an instance of Blink and of cc) cannot directly issue calls to the 3D APIs provided by the OS (GL / D3D). For that reason we use a separate process to access the device. We call this process the GPU Process. The GPU process is specifically designed to provide access to the system's 3D APIs from within the Renderer sandbox or the even more restrictive Native Client "jail". It works via a client-server model as follows:

https://www.chromium.org/developers/design-documents/gpu-accelerated-compositing-in-chrome

`Chrome` by default uses a separate process for `GPU Acceleration` due to it's sand boxing. By default there is no `Sandboxing` in `CefSharp` (cannot directly link the native `.lib` file required into a `Managed Exe`). The little I've read about the topic suggests that `In Process GPU` is used for `Android`, so should be a fairly well tested piece of code, though not on `Windows`. If you use this method and experience any rendering problems then you'll have to raise them with `Chromium`.

`Intel GPU's` are notoriously problematic and it's quite common to disable `GPU` acceleration for older models as they simple don't render properly. `Chrome` maintains list of problem cards and workarounds. (there are versions specific to each branch, open `chrome://gpu/` and there will be a link to the exact version that's relevant to the branch you are using).

https://cs.chromium.org/chromium/src/gpu/config/software_rendering_list.json
https://cs.chromium.org/chromium/src/gpu/config/gpu_driver_bug_list.json

As a general note, making sure you have the latest graphics drivers, if you look at the `Software Rendering List` you'll see that quite a few entries are driver version specific.

Closing as this isn't a bug in `CefSharp`, just a byproduct of some `Chrome` changes.
