### ISSUE TITLE
'System.IO.FileLoadException' occurred in ... Additional information: A procedure imported by 'CefSharp.Core.dll' could not be loaded.

### ISSUE THREAD

**Issue by Dj-rEPKa** [cefsharp/CefSharp#2337]
I have different solutions of same project for various API versions.
Except one it`s OK, CefSharp works fine without any exceptions, however last one shows this:
"An unhandled exception of type 'System.IO.FileLoadException' occurred in Name.dll Additional information: A procedure imported by 'CefSharp.Core.dll' could not be loaded. occurred"

Beyond Compare shows only diversity in .Net Framework with last solution where Exception shows up and there .Net Framework 4.7 is used (it`s last version to support and i can`t downgrade it).

CefSharp requires at least .Net 4.5.2 (Last version to support .Net 4.0 is 49)
Is it OK to use .Net 4.7? Maybe other options to solve this?

**Comment by amaitland** [comment]
> Is it OK to use .Net 4.7?

`.NET 4.7.1` works fine for me, I'd be surprised if `4.7` was any different.

Does your project have `Generate serialization assembly` enabled by any chance?

**Comment by Dj-rEPKa** [comment]
@amaitland 
Thanks for the answer.
Yep, `.NET 4.7` works fine (tested in simple `WinForm` app).

> Does your project have `Generate serialization assembly` enabled by any chance?
Nope, it`s not.

Honestly, I think this may be a problem caused by `Revit Pre-release` version, however i`d like to know exactly.
Almost confident, it couldn't be some system requirements problem like missed `C++ Retribution` or others because all the things works fine with other Revit versions from 2016 till 2018.

**Comment by amaitland** [comment]
The typical list of problems that match your error message are listed at https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#Runtime_dependencies

Quick `Google` and others appear to be using `Revit`, see https://stackoverflow.com/questions/38748726/embedding-cefsharp-in-a-plugin-for-revit 

Will leave this open for a little while, will close in a few weeks if no further comment as it doesn't appear to be a bug in `CefSharp`.

**Comment by Dj-rEPKa** [comment]
@amaitland 
_Thanks for answering!_

All my projects build into same `Output` folder, thats why it could not be `Runtime_dependencies` issue.

> Quick Google and others appear to be using Revit, see https://stackoverflow.com/questions/38748726/embedding-cefsharp-in-a-plugin-for-revit

Surfing the net was helpless. `Revit 2019` is not officially published yet, did not find any opened problems with it, however they are, while other `Revit` versions work fine with `CefSharp` 😞

As usual, `Autodesk` publish new version of `Revit` on the end of April, will wait for that and will try using `CefSharp` on approved API, then will give response.

**Comment by Dj-rEPKa** [comment]
@amaitland 
Ok, Autodesk Revit 2019 had been released.
And the issue has disappeared itself. Arguably that was pre-release version problem, dunno exactly, yet thank`s for Your help!

**Comment by iandarlingautoscribe** [comment]
Hello,

I've come across this issue in our application as well, but dependant at runtime on the database engine we connected to!

The environment in question here is:
CEFSharp 63
Windows 7 SP1 (x64 and x86)

When running our application against SQL Server, there's no problem, however when we switch the application to look at an Oracle database (using Oracle Client 11.2), we get the above message, even though it's the same installation of our application otherwise (no binary changes - it's basically a connection string change in app.config)

From this I can conclude that while we've installed the dependencies correctly (VC++ 2013 Redist, etc), and there's some other issue (such as DLL Load Order?) occurring which causes it to fail.

I have had success here changing the order in which things are initialised.

Moving the CEFSharp initialisation to be prior to any Oracle data access being made seems to have corrected the problem here, although we haven't completed our testing.

Hopefully this helps other people with the same problem.
