### ISSUE TITLE
WPF/OffScreen require setting windowless_rendering_enabled in 67+

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#2431]
See http://magpcss.org/ceforum/viewtopic.php?f=6&t=16077

To-do update with more details later. Just adding as placeholder

**Comment by amaitland** [comment]
https://bitbucket.org/chromiumembedded/cef/src/514ced40ceffa16966d9dee23a253014faf74d72/libcef/browser/osr/render_widget_host_view_osr.cc?at=3396&fileviewer=file-view-default#render_widget_host_view_osr.cc-243

**Comment by joaompneves** [comment]
Probably this should be set as true by default on CefSettings?
I upgraded to the latest version and got a blank screen, because I'm doing Cef initialization with custom settings. I sepnt a couple of hours debugging to search fo the problem and had to go through the list of latest changes until I found this. Setting the default to true would prevent further problems.

**Comment by amaitland** [comment]
It's not that straightforward or I would have already done it. Have a think about the problem further, open to suggestions.

**Comment by bddckr** [comment]
Isn't this already handled by the browser class trying to do it in its constructor?
https://github.com/cefsharp/CefSharp/blob/9d4504db9911b883a0e0b32837730507ee1f3cb7/CefSharp.OffScreen/ChromiumWebBrowser.cs#L277-L286

This obviously fails if CEF is already initialized. How about throwing an exception from now on when CEF is initialized but the flag not being set to true?
That would take care of blowing up in my face early, rather than me overlooking this in any changelog etc.

**Comment by amaitland** [comment]
https://bitbucket.org/chromiumembedded/cef/issues/2447/osr-add-support-for-surface

**Comment by amaitland** [comment]
Issue #2477 implements `Option 2`, so `WindowlessRenderingEnabled` will be set accordingly.

This is a minor breaking change.
