### ISSUE TITLE
Dispose() doesn't free Ram

### ISSUE THREAD

**Issue by ukushu** [cefsharp/CefSharp#2437]
Steps to reproduce: 
1. check memory usage
2. create instance
3. open any page
4. check memory usage
5. Cef.Shutdown(); + Browser.Dispose();
6. check memory usage
7. Force CG.Collect();

expected result:
1. ~6 mb is used
5. ~110 mb used
6. ~6 mb used
7. ~6 mb used

actual result:
1. ~6 mb is used
5. ~110 mb used
6. ~110 mb used
7. ~110 mb used

was used Cef.Winforms 63.0.3
VS 2017
x86
Win10 x64

**Comment by amaitland** [comment]
> expected result:
> 
> ~6 mb is used
> ~110 mb used
> ~6 mb used
> ~6 mb used

What are you basing this expectation on? Which memory profiler did you use? What your seeing is pretty much what I expect.

- `libcef.dll` is loaded upon creation of the first `ChromiumWebBrowser` instance or a call to `Cef.Initialize`, it's almost `100mb`. `VC++` takes control over loading dlls and provides no mechanism for unloading them. You can in theory manually call `LoadLibrary` and `FreeLibrary`.

- `Chromium` leaks memory on `Shutdown` by design, see https://www.chromium.org/developers/coding-style/important-abstractions-and-data-structures#TOC-Singleton-base::LazyInstance If this is a problem for you then you'll need to choose a browser that's based on something other than `Chromium`.

**Comment by ukushu** [comment]
I think `FreeLibrary()` method will help me. Thanks a lot!

But in the same time this is non-logic behavior. Dispose() of CEF must to free memory, I believe... 
I think you may close the ticket if you want.

**Comment by amaitland** [comment]
Dispose is responsible for freeing references and releasing unmanaged resources, if you have a reproducible leak then post the details. 

.Net doesn't support unloading managed dlls see https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/assemblies-gac/how-to-load-and-unload-assemblies
