### ISSUE TITLE
"ChromiumWebBrowser" does not exist in the namespace "clr-namespace:CefSharp.Wpf;assembly=CefSharp.Wpf"

### ISSUE THREAD

**Issue by TriStarGod** [cefsharp/CefSharp#2558]
- **What version of the product are you using?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch? Please include the exact version number you are using (no ambiguous statements like `Latest from Nuget`)
Nuget - CefSharp.Wpf v67.0.0

- **What architecture x86 or x64?**
x64
- **On what operating system?**
Win10
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF
- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reproduce your problem.
    - Please no binary (zip, etc) links, fork the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) and push your changes to `GitHub`. (Alternatively use a code sharing service list `Gist` or `Pastebin`).
Setup project for x64
Installed Cefsharp.WPF via Package Manager
Inserted `xmlns:cefSharp="clr-namespace:CefSharp.Wpf;assembly=CefSharp.Wpf"`
and `<cefSharp:ChromiumWebBrowser Grid.ColumnSpan="2" Grid.Row="2" Address="https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions" />`
as outlined in guide within a MahApps MetroWindow. Also confirmed same error even in standard wpf project.
- **What is the expected output? What do you see instead?**
Expected to display webpage.
Instead outputs error message:

1. The name "ChromiumWebBrowser" does not exist in the namespace "clr-namespace:CefSharp.Wpf;assembly=CefSharp.Wpf"
2. Displays designer warning Invalid Markup
3. ~~Does not open / display webpage when viewed.~~

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

**Comment by amaitland** [comment]
See https://github.com/cefsharp/CefSharp.MinimalExample for a working example

**Comment by SolarIceMedia** [comment]
how is this not a bug ? its saying that it doesn't exist? sounds like a bug to me. stop being lazy and pawning it off and fix the issue

**Comment by amaitland** [comment]
> stop being lazy and pawning it off and fix the issue.

@SolarIceMedia The packages work as expected for older versions of visual studio,  I've attempted to get this resolved with Microsoft and they're said the behaviour is now by design see https://github.com/dotnet/project-system/issues/4158

If you migrate to the package reference Nuget implementation initial build works as expected. All you have to do with the older packages.config implementation is close and reopen the solution as listed in the post installation notes.

If you'd like to sponsor my time in overhauling the packages to change this then I'm happy to discuss that. As for lazy I've spent literally thousands of hours over almost 6 1/2 years supporting and maintaining this project. You've paid nothing,  contributed nothing and here you are thanking me for my efforts with borderline abuse....thanks  👎
