### ISSUE TITLE
Issue with ExecuteJavaScriptAsync and console.log

### ISSUE THREAD

**Issue by RobotGizmo** [cefsharp/CefSharp#2718]
Hello! I'm using the WinForms v71 version of CefSharp. If I call this:

browser.GetBrowser().MainFrame.ExecuteJavaScriptAsync("console.log('test');");

I don't see anything in my developer console. If I run a script with errors I see those errors in the console. Is there something I need to do to have my console.log and console.warn messages appear in the dev tools console? This seems like a bug in either Cef or CefSharp, but forgive me if I'm missing something.

**Comment by amaitland** [comment]
> This seems like a bug in either Cef or CefSharp

`CefSharp` is just a wrapper, in this instance it does a few checks and calls the `CefFrame::ExecuteJavaScript` method. It's actually unlikey a bug in `CEF` either, most common cause of this issue is executing `JavaScript` before the `V8Context` has loaded. See https://github.com/cefsharp/CefSharp/wiki/General-Usage#when-can-i-start-executing-javascript

For reference https://github.com/cefsharp/CefSharp/blob/cefsharp/71/CefSharp.Core/Internals/CefFrameWrapper.cpp#L232

A quick check with https://github.com/cefsharp/CefSharp.MinimalExample and it works as expected. See below for the code I used.

```c#
private void OnLoadingStateChanged(object sender, LoadingStateChangedEventArgs args)
{
	SetCanGoBack(args.CanGoBack);
	SetCanGoForward(args.CanGoForward);

	browser.GetMainFrame().ExecuteJavaScriptAsync("console.log('CefSharp Test');");

	this.InvokeOnUiThreadIfRequired(() => SetIsLoading(!args.CanReload));
}
```

Closing this as `invalid`. In future please read https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md before opening an `Issue`, thanks.
