### ISSUE TITLE
Cef browser locks up upon closing a dialog that has a javascript alert still showing

### ISSUE THREAD

**Issue by Yokomoko** [cefsharp/CefSharp#2819]
**Steps to Reproduce**

1. Open a popup dialog box
2. Trigger a javascript alert in that popup dialog box
3. Close that popup dialog box in code (Alternatively, force closing this window with Window Detective also replicates the issue)
4. Now all windows inside Cefsharp won’t focus anything, unable to click anything, but can still press F5 and the page refreshes.

**Expected Output**

The expected output would be for Cef to close the dialog box properly and then close the popup window.

**Operating System/Version**

Visual Studio 2017, Nuget CefSharp 73.1.13, Windows 10 &amp; Windows 8
Edit: Using Winforms

**Reproducible on the sample application?**

Yes, on version of the same and the latest version

**Reproduced on Google Chrome of the same version?**

Not reproducible on Google Chrome - Their javascript alerts are handled differently from Cef which opens a message box instead.

I've reported this on the Cef Bitbucket but they have stated this would be a CefSharp issue?

**Comment by amaitland** [comment]
Closing as `upstream`.

https://bitbucket.org/chromiumembedded/cef/issues/2698/cef-browser-locks-up-upon-closing-a-dialog

**Comment by amaitland** [comment]
> https://bitbucket.org/chromiumembedded/cef/issues/2698/cef-browser-locks-up-upon-closing-a-dialog

Some quick comments about the issue you opened that might get you a better result

- Remove all references to `CefSharp`, all that matters is the problem reproduces with `cefclient`.
- Instead of `Yes, on version of the same and the latest version` provide exact versions you tested with. 
- Provide a Url for testing, makes life so much easier (update your list of steps to reproduce based around the url).

Best of luck.
