### ISSUE TITLE
WPF - Update ZoomLevel  xml doc re same origin behaviour

### ISSUE THREAD

**Issue by David-Loving** [cefsharp/CefSharp#2834]
So working on pages sharing the same sub domain in chrome have the same zoom level.

- I create 2 ChromiumWebBrowser controls in my WPF application pointing at same website.
- Change the ZoomLevel in the first control.

Both windows seem to visual zoom to the same level but when you ask the second control what it's ZoomLevel is it reports the original value and not the updated zoom.

**Comment by amaitland** [comment]
Please fill out the bug report at https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

Are both controls visible at the same time?

**Comment by David-Loving** [comment]
CefSharp.WPf version 71.0.2
Architecture x64
Windows 10
Using WPF

Steps

- I create 2 ChromiumWebBrowser controls in my WPF application pointing at same website or websites on the same sub domain, for example http://www.bbc.co.uk and http://www.bbc.co.uk/news.
- Change the ZoomLevel in the first control.

Out come/error
Both windows content seem to visual zoom to the same level but when you ask the second control what it's ZoomLevel is it reports the original value and not the updated zoom.

Are both controls visible at the same time?
Yes.

**Comment by amaitland** [comment]
The `XML Doc` for `ZoomLevel` should be updated to reflect that this is the expected behaviour. `CEF` doesn't provide any sort of notification for zoom change so we have no means of tracking between browser instances when they are all visible. It's not practical to try and track this manually as there are many different factors `Chromium Process Model`, `Request Context`, etc that change the behaviour of which browsers share a render process.

For `Tabbed` browsers we update the zoom level when the browser becomes visible to get around this https://github.com/cefsharp/CefSharp/blob/cefsharp/73/CefSharp.Wpf/ChromiumWebBrowser.cs#L1858

Your options are:
- You can specify a [Request Context](https://github.com/cefsharp/CefSharp/wiki/General-Usage#request-context-browser-isolation) for each `ChromiumWebBrowser` instance to isolate them and subsequently have independent zoom level. 
- Use the `CEF API` methods directly and implement your own zoom handling see http://cefsharp.github.io/api/73.1.x/html/M_CefSharp_IBrowserHost_GetZoomLevelAsync.htm and http://cefsharp.github.io/api/73.1.x/html/M_CefSharp_IBrowserHost_SetZoomLevel.htm

> Are both controls visible at the same time?
> Yes.

I'd ask that if you open another issue at later date that you provide more detail in your steps to reproduce, ideally a code example that clearly reproduces your problem.

**Comment by amaitland** [comment]
XML Doc has been updated, at the moment that's likely the best we can do.
