### ISSUE TITLE
Assembly Issue(s)

### ISSUE THREAD

**Issue by Phantom11265** [cefsharp/CefSharp#2919]
So after installing your NuGet package, I restarted my Visual Studio (2019) and added the namespace for your guy's stuff (I'm using WPF). 
![image](https://user-images.githubusercontent.com/49042422/66000346-c1d59600-e48e-11e9-8dab-fb4dc2a920b3.png)
I put the ChromiumWebBrowser inside a grid with the name chrome_browser.
![image](https://user-images.githubusercontent.com/49042422/66000779-afa82780-e48f-11e9-92ad-b489393e804c.png)
The public method at the very top of the screenshot is my main function and when I tried calling chrome_browser.Address = subdir; it would give me an error.
![image](https://user-images.githubusercontent.com/49042422/66001067-42e15d00-e490-11e9-83a5-a712b8e43e5b.png)
Error:
![image](https://user-images.githubusercontent.com/49042422/66001202-8b007f80-e490-11e9-885b-7b0afa39435d.png)
It was frustrating however I did find this fix from StackOverFlow: https://stackoverflow.com/questions/52394485/how-to-get-cefsharp-to-work-with-configuration-anycpu-in-vs-common-library
I only instantiated the event and called it before InitializeComponent(): in my main function. I didn't do the second part of the answer in that link. It fixed my issue but I do think this is a weird bug. 
FYI: my subdir is just a pdf file that's in my local drive (just in case you were wondering).

**Comment by Phantom11265** [comment]
Please review.

**Comment by amaitland** [comment]
If you believe this issue was closed in error then to be reconsidered for review please edit your original question,  completing the bug report template provided at https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

- An actual example that reproduces the issue is required, please fork https://github.com/cefsharp/CefSharp.MinimalExample (squash your changes into a single commit then push them to `GitHub`.)
- No images of exceptions see http://idownvotedbecau.se/imageofanexception/
- No images of code http://idownvotedbecau.se/imageofcode
