### ISSUE TITLE
NullReferenceException at ClientAdapter.OnProcessMessageReceived

### ISSUE THREAD

**Issue by joaompneves** [cefsharp/CefSharp#2971]
- **What version of the product are you using?**
    - 75.0.14

- **What architecture x86 or x64?**
    - x64

- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WPF

- **What steps will reproduce the problem?**
    - I cannot reproduce this problem systematically 

- **What is the expected output? What do you see instead?**
    - Getting a NullReferenceException at ClientAdapter.OnProcessMessageReceived

- **Please provide any additional information below.**
    - Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
at CefSharp.Internals.ClientAdapter.OnProcessMessageReceived(ClientAdapter* , scoped_refptr<CefBrowser>* browser, scoped_refptr<CefFrame>* frame, cef_process_id_t source_process, scoped_refptr<CefProcessMessage>* message) in d:\a\1\s\cefsharp.core\internals\clientadapter.cpp:line 1225

That line contains the following code:
```
for (auto i = 0; i < static_cast<int>(arguments->GetSize()); i++)
```

I'm not C++ fluent, but either the `arguments` are null, the cast throws the exception or the optimizations are somehow tricking me and the problem is around this line.
Can anyone shed a light on this problem? What do you think it can be? 
I don't expect the arguments to be null, at least I don't see how that can happen, looking at the code on the browser side. Unfortunately this crash happens quite often on the test machines, but I don't know yet how to reproduce.

**Comment by amaitland** [comment]
I wouldn't expect that line to throw a `NullReferenceException`.

> * 75.0.14

Which version are you using? The latest official release is `75.1.143`

> * d:\a\1\s\cefsharp.core\internals\clientadapter.cpp:line 1225

This would indicate you are using a custom build, does the problem reproduce with the official release packages?

**Comment by joaompneves** [comment]
The custom build is = to the CefSharp/75 but contains the fixes for which I have already made pull requests. The changes made don't touch this area.

**Comment by amaitland** [comment]
> cefsharp/75...OutSystems:cefsharp/75-patched

Unfortunately that's not really an accurate comparison, the https://github.com/cefsharp/CefSharp/commits/cefsharp/75 branch has the changes from the last `PR` you submitted. The [75.1.143](https://ci.appveyor.com/project/cefsharp/cefsharp/builds/28573359) release includes those changes.

You appear to have made some other changes which haven't been submitted.

**Comment by joaompneves** [comment]
I don't think the differences are relevant. The one (difference) that has not been submitted yet, is around network requests (ResourceHandler.cs) - to make it more robust, since the current implementation is not thread safe.
The other change in the ClientAdapter.cpp was introduced after (recently) I saw it happening, to log more information about the crash.

**Comment by snowball58** [comment]
My team has encountered this exact issue with the following configuration:

**What version of the product are you using?**

85.3.130

**What architecture x86 or x64?**

x64

**On what operating system?**

Win10

**Are you using WinForms, WPF or OffScreen?**

WinForms

**What steps will reproduce the problem?**

We have not modified CefSharp or CEF in any way. The issue was encountered several hours into a "soak" of our product, which involved opening and closing browser instances at a high frequency over an extended period of time. This seems to be rare and difficult to reproduce.

**Please provide any additional information below.**

System.NullReferenceException: Object reference not set to an instance of an object.
   at CefSharp.Internals.ClientAdapter.OnProcessMessageReceived(ClientAdapter* , scoped_refptr<CefBrowser>* browser, scoped_refptr<CefFrame>* frame, cef_process_id_t source_process, scoped_refptr<CefProcessMessage>* message)

**Comment by andrewzjl** [comment]
My team has encountered this exact issue with the following configuration:
What version of the product are you using?

86.0.241

What architecture x86 or x64?

x64

On what operating system?

Win10

Are you using WinForms, WPF or OffScreen?

WPF

What steps will reproduce the problem?

We just use the cefsharp lib from NUGET. This seems to be rare and difficult to reproduce. It might happen when the browser instances are created and closed frequently, or happens when try to close a browser instance which was opened and deactivated few minutes.

Please provide any additional information below.

System.NullReferenceException: Object reference not set to an instance of an object.
at CefSharp.Internals.ClientAdapter.OnProcessMessageReceived(ClientAdapter* , scoped_refptr* browser, scoped_refptr* frame, cef_process_id_t source_process, scoped_refptr* message)

https://github.com/cefsharp/CefSharp/blob/9ff6b35ddff0db803e9fed23ebb67f9f4c9f7d1d/CefSharp.Core/Internals/ClientAdapter.cpp#L1279

**Comment by amaitland** [comment]
Version 90 includes some fixes for nre in OnProcessMessageReceived

If the problem still occurs after upgrading to version 91 (The current supported version) then please open a new issue.

**Comment by andrewzjl** [comment]
> Version 90 includes some fixes for nre in OnProcessMessageReceived
> 
> If the problem still occurs after upgrading to version 91 (The current supported version) then please open a new issue.

Thanks for the information. I'll have a try.
