### ISSUE TITLE
CefSharp.Common.targets - Improve PlatformCheck error message

### ISSUE THREAD

**Issue by R0Wi** [cefsharp/CefSharp#3009]
- **What version of the product are you using?**
    - current master

- **What architecture x86 or x64?**
    - both

- **On what operating system?**
    -  Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - `WinForms`
- **What steps will reproduce the problem?**
    - Create a new `WinForms` project
    - Change the `Platform target` in the projectsettings to `x86` or `x64`  
![image](https://user-images.githubusercontent.com/19730957/72144905-a76a5d00-3399-11ea-8083-83e7c0693924.png)
    - Try to build the project
    - Error output:
    ```
    CefSharp.Common contains unmanaged resoures, set your project and solution platform to x86 
    or x64. Alternatively for AnyCPU Support see https://github.com/cefsharp/CefSharp/issues/1714		
    ```

- **What is the expected output? What do you see instead?**
    - Project should build because i explicitly set the target to `x86` (even though the compiler-profile is still named `AnyCPU`)

- **Please provide any additional information below.**
    - Related to #1714

**Comment by amaitland** [comment]
> * Change the `Platform target` in the projectsettings to `x86` or `x64`

@R0Wi If your **solution** targets `AnyCPU` and you haven't added `<CefSharpAnyCpuSupport>true</CefSharpAnyCpuSupport>` to your project then the error you are seeing is the current expected behaviour.

Setting `<CefSharpAnyCpuSupport>true</CefSharpAnyCpuSupport>` in your project file will satisfy the `PlatformCheck` check.

> CefSharp.Common contains unmanaged resoures, set your project and solution platform to x86 
> or x64. Alternatively for AnyCPU Support see https://github.com/cefsharp/CefSharp/issues/1714

The error message could be improved, and outputting the current solution target is an excellent idea, thanks for the suggestion 👍 Issue title updated to remind me to improve the message.

---

All the `target/props` conditions rely on `$(Platform)` currently, whilst we could use `$(PlatformTarget)` in the `.targets` files, the `props` files are included before `$(PlatformTarget)` is defined. Having a mix of `$(PlatformTarget)` and `$(Platform)` would likely result in unexpected behaviour and create lots of support issues.

The current solution is far from perfect and may not be the behaviour you were expecting, it is the intended behaviour. I have a plan to release a more modern set of packages that will simply target `x86` or `x64` the relevant issue is #2795

**Comment by R0Wi** [comment]
@amaitland thanks for your feedback.

So in our case we have the situation that we're targeting `x86` but we compile our projects with a profile named `AnyCPU`. What we did when we created the projects is just to leave the default profile name (`AnyCPU`) of Visual Studio, but to change the target from `AnyCPU` to `x86`. So we are facing the configuration shown in the initial image above. Problem here is that we got compiler errors after adding the `CefSharp`-dependency. In our case i think this is not an correct behaviour because we are indeed compiling for `x86` but with a profile named `AnyCPU`.

Currently we have about 300 Solutions so renaming all profiles would be a little painful :-)

Any other workarounds we could use in our case?

**Comment by amaitland** [comment]
> So in our case we have the situation that we're targeting `x86` but we compile our projects with a profile named `AnyCPU`. What we did when we created the projects is just to leave the default profile name (`AnyCPU`) of Visual Studio, but to change the target from `AnyCPU` to `x86`. So we are facing the configuration shown in the initial image above. Problem here is that we got compiler errors after adding the `CefSharp`-dependency.

Thanks for the detailed explanation. I am aware of the limitation

> In our case i think this is not an correct behaviour because we are indeed compiling for `x86` but with a profile named `AnyCPU`.

Unfortunately the `.props` files don't know that as `PlatformTarget` is defined after the `.props` files are included, e.g. https://github.com/cefsharp/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.WinForms/CefSharp.MinimalExample.WinForms.csproj#L33

> We don't like to add the `<CefSharpAnyCpuSupport>true</CefSharpAnyCpuSupport>` because we don't support `AnyCPU`. Any other workarounds we could use in our case?

Adding `CefSharpAnyCpuSupport` with a code comment or creating your own `.targets` file that includes the `CefSharpAnyCpuSupport` property and any additional targets you require to copy only the `x86` files to your bin folder would me the option I would choose.

Otherwise your left with `MsBuild` hacks like overriding a `Target Overriding`.

**Comment by amaitland** [comment]
I've changed the message, hopefully it's clearer see https://github.com/cefsharp/CefSharp/blob/cefsharp/79/NuGet/CefSharp.Common.targets#L4

I've also added some more detail to the [Quick Start AnyCPU](https://github.com/cefsharp/CefSharp/wiki/Quick-Start#anycpu-support) section.

When https://github.com/cefsharp/CefSharp/issues/2795 is resolved you will be able to install a specific `x86` or `x64` package (will require `Nuget 4.0+`)
