### ISSUE TITLE
Migrate from ResourceHandler.GetMimeType to Cef.GetMimeType

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#3041]
The current list of mappings is outdated. Newer fonts and audio formats have been added and the list should be updated. Rather than update our own list we can leverage from [Cef.GetMimeType(string)](http://cefsharp.github.io/api/79.1.x/html/M_CefSharp_Cef_GetMimeType.htm) to perform file extension to mimeType mapping. 

---

Previously I was going to update this mapping, decided against trying to maintain our own mapping as using the Chromium implementation is quite simple.

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types
- https://cs.chromium.org/chromium/src/net/base/mime_util.cc?sq=package:chromium&g=0&l=147
- http://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by amaitland** [comment]
http://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by amaitland** [comment]
In commit https://github.com/cefsharp/CefSharp/commit/2b47cf56ce0d39a504177698f1015e9e4af143fe the following are now **Obsolete**

```c#
//Replace
ResourceHandler.FromString(string, string)
//With
ResourceHandler.FromString(resource, mimeType: Cef.GetMimeType(extension));
```

```c#   
//Replace
ResourceHandler.GetMimeType(extension);
//With
Cef.GetMimeType(extension);
```

**Comment by amaitland** [comment]
https://github.com/cefsharp/CefSharp/wiki/General-Usage needs updating

**Comment by amaitland** [comment]
> https://github.com/cefsharp/CefSharp/wiki/General-Usage needs updating

Updated in https://github.com/cefsharp/CefSharp/wiki/General-Usage/_compare/10bf10d2f28e9ad4a0afd95cdf151790607755e1...64a7e45802f899370e5a00a6ad7e694c61e04360

**Comment by Wupval** [comment]
Hello, I know it is intended, that the function ResourceHandler.GetMimetype() is replaced with Cef.GetMimeType(), but since the update, we have some crashes because of it, as Chromium only provides a rather small mapping for mime-types. For example, there will be an ArgumentException in the FolderSchemeHandlerFactory when trying to load .woff2 files or .ttf files. ResourceHandler.GetMimetype() didn’t interpret them as font/woff2 or font/ttf, but it did return application/octet-stream as default, so nothing crashed, and the fonts loaded. May I suggest that a default value would be added to Cef.GetMimeType()? Others may also have similar problems, as the change is not listed as breaking change (I think, if it is, please correct me on this) and could be overlooked.

**Comment by jankurianski** [comment]
@Wupval See #3105 where @amaitland made a note to that effect as he also observed `.woff2` was missing from `Cef.GetMimeType()`.

**Comment by amaitland** [comment]
@Wupval Thanks for the feedback. I'll add a default of `application/octet-stream` and possibly a custom mapping to correctly support `woff2` and other fonts.

**Comment by amaitland** [comment]
I've made some improvements that hopefully resolves the exception that you are seeing.

- `application/octet-stream` is now returned if no mimeType mapping is found
-  Added some custom mappings for a small number of types that should be handled, it's possible to add your own mimeType mappings to this dictionary. This mapping is only used if `CefGetMimeType` doesn't return a mapping.
- Added a `Theory` based `XUnit` test

If you experience any further exceptions after this then please provide a failing test case.

Changes will be in the final `81` release, see commit https://github.com/cefsharp/CefSharp/commit/99cc2d5030e48b1f05b1aa847216a47bd0bc3eb2 for details.
