### ISSUE TITLE
PDF generation crashes when a custom margin type is specified

### ISSUE THREAD

**Issue by GrabzIt** [cefsharp/CefSharp#3043]
- What version of the product are you using? 79.1.350

- What architecture? x86

- On what operating system? Win10

- Are you using WinForms, WPF or OffScreen? OffScreen

- What steps will reproduce the problem?
If you specify pdfSettings.MarginType = CefPdfPrintMarginType.Custom; the PDF task will not complete.

**Comment by amaitland** [comment]
I haven't tested yet though I suspect this is a `CEF` issue, which is related to https://bitbucket.org/chromiumembedded/cef/issues/2694/pdf_print_margin_custom-settings-are

I suspect that `Chrome` has made changes to it's `PDF` implementation and `CEF` needs to be updated to support custom margins.

**Comment by NeomMob** [comment]
in WPF, no crash but no difference between custom margins and no margin.

**Comment by amaitland** [comment]
I can reproduce the crash and I've reviewed the chromium code changes. This is still issue https://bitbucket.org/chromiumembedded/cef/issues/2694/pdf_print_margin_custom-settings-are 

See https://bitbucket.org/chromiumembedded/cef/issues/2694/pdf_print_margin_custom-settings-are#comment-56342659 for my comments on the subject.

**Comment by amaitland** [comment]
Changes were merged into `CEF`, I've updated to the latest version in https://github.com/cefsharp/CefSharp/commit/f566d99b129006b797ddb9e72dada301d144bb48

Quick test and custom margins appear to be working, report at https://bitbucket.org/chromiumembedded/cef/pull-requests/290/change-_cef_pdf_print_settings_t-custom/diff#comment-146452726 says the changes are working as expected.

Will be fixed in the `81` release.
