### ISSUE TITLE
Winform ImeCommitText Method do not work

### ISSUE THREAD

**Issue by Green1ee** [cefsharp/CefSharp#3267]
For Example:
```
        Task.Run(async delegate
            {
                var host = this.chromeBrowser.GetBrowserHost();

                host.SendMouseClickEvent(843, 270, MouseButtonType.Left, false, 1, CefEventFlags.None);
                host.SendMouseClickEvent(843, 270, MouseButtonType.Left, true, 1, CefEventFlags.None);
                await Task.Delay(3000);
                host.ImeCommitText("words", null, 0);  // run successfully, but no effect.
            }
        );
```

**Comment by amaitland** [comment]
ImeCommitText is intended to be used by the WPF/OffScreen versions. 

You'll need to report your problem on https://magpcss.org/ceforum/index.php as implemented in CEF/Chromium. By all means post a link back here for reference. 

Closing as upstream.

**Comment by amaitland** [comment]
You can try using DevTools and https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-insertText as an alternative. 

For details on executing commands see  https://github.com/cefsharp/CefSharp/issues/3165

It's important to remember that CefSharp is just one of many chromium embedded framework wrappers and doesn't actually implement these features we just allow you to call the C++ methods from .Net 

ImeCommitText is not something we can fix directly and reporting the problem here doesn't inform the CEF developers there is an issue.
