### ISSUE TITLE
cefSharp wpf Keyboard input do not appear in the browser. 

### ISSUE THREAD

**Issue by JPipe** [cefsharp/CefSharp#362]
I have a winform app hosting a wpf form in which the cef browser is added (don't ask this is a legacy product...) . 
I am able to navigate, evaluate script, but cannot get the the keyboard input to appear in the browser. 
Running in the debugger, I can see the keystrokesprocessed by  the CefSharp.wpf  WebView event (OnPreviewKey & SourceHook), but never seem to make it to the browser UI. 
Other keys such as tabs & arrow keys navigate fine in the browser but no characters seems to make it into the UI. 

It's almost as if the key is being processed correctly, but is sent to the wrong destination.

Can anyone help?

Thanks, 

Jan

**Comment by wiscow** [comment]
I am currently experiencing the same issue that @JPipe was experiencing.  Is there any way to get the this to work using ElementHost.EnableModelessKeyboardInterop instead of ShowDialog.  One of our requirements for our application is to not show the WPF portion of our applciation as a dialog.  This is causing a major roadblock for us.  

Thanks!

**Comment by sowrab1994** [comment]
I am facing this issue too.  Opening a Wpf Window inside Winforms, not able to send any keystores to wpf window.  I can't make it a Modal dialog due to requirement of application.
