### ISSUE TITLE
DevToolsClient.Emulation methods doesn't affect dynamically created frames

### ISSUE THREAD

**Issue by n303ef** [cefsharp/CefSharp#4394]
We can override User Agent, locale and some other settings through `DevToolsClient.Emulation` methods but they doesn't affect frames that created dynamically by JavaScript. These frames can access original browser settings which were set on `Cef.Initialize()`.

To reproduce problem:
1. Redefine UserAgent:
```
_ = client.Emulation.SetUserAgentOverrideAsync("Some UserAgent");
//or: _ = client.Network.SetUserAgentOverrideAsync("Some UserAgent");
```

2. Attach such code to `ChromiumWebBrowser.FrameLoadEnd`:
```
string js = "alert(navigator.userAgent);";
e.Frame.ExecuteJavaScriptAsync(js);
```
3. Load any page with is dynamically adding frames. For example, it's a website with google ads:
```
browser.LoadUrl("https://browserleaks.com/");
```

What messages we see after that:

Some UserAgent
Some UserAgent
Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

**Comment by amaitland** [comment]
This would need to be fixed in `CEF` or `Chromium`. Not sure which though.

First try with the latest `M110` release. If the problem reproduces then I'd probably start by trying say `puppeteer` or `puppeteer-sharp` and seeing if the problem reproduces there.

It's quite possibly something that needs to be fixed in `CEF` which has it's own [issue tracker](https://bitbucket.org/chromiumembedded/cef/).

In future please use the [Bug Report Template](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Closing as `upstream`.
