### ISSUE TITLE
Feature Request - RegisterJsObject on the fly

### ISSUE THREAD

**Issue by malisert** [cefsharp/CefSharp#602]
Hi,

I know that RegisterJsObject is not working on the fly binding. All registration should be done at creation time. But it will be good to register an object at anytime to implement MVVM.  For example with below code:

``` c#
public void RedirectToView(string view)
{
    var browser = App.UnityContainer.Resolve<IWpfWebBrowser>();
    var viewModel = ViewModelFactory.GetViewModel(view, browser);
    browser.RegisterJsObject("viewModel", viewModel);
    browser.Load(viewModel.ViewUrl);
}
```

Are you considering implementing the on the fly javascript binding in the near feature?

**Comment by rassilon** [comment]
It seems like just adding a method to `IRenderProcess` along the lines of `UpdateRegisteredObjects` ought to be implementable without too much pain. The method would requery IBrowserProcess for the list of registered objects, or query a new `AddedRegisteredObjects` that might consume a browserId/frameId or something.

(I'm not going to do this, btw. I would rather have an easier way of binding to JS supplied anonymous functions that the browser process could callback to.)

**Comment by sambengtson** [comment]
Just casually looking at this, I thought that by re-calling SendProcessMessage
```
_cefBrowser->SendProcessMessage(CefProcessId::PID_RENDERER, jsRootObjectMessage);
```

after binding would re-load the javascript objects.  Does not seem to work but do you guys know if I'm way off base here?

**Comment by amaitland** [comment]
> Does not seem to work but do you guys know if I'm way off base here?

That message basically updates a couple of variables.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp#L386

The real work happens when the `CefV8Context` is created.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp#L94

Simplest approach is likely to send a new message containing only the objects that have yet to be registered. Get the `CefV8Context` for the relevant `CefFrame` then `Bind` the new objects.

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefFrame.html#GetV8Context%28%29

Overall it shouldn't be too hard (a lot has changed since the original issue was created)

**Comment by perlun** [comment]
Incredibly old issue, so closing for now. Submit a new issue referring to this one if you find issues with the current implementation.
