### ISSUE TITLE
Issue when CEF is put inside listbox

### ISSUE THREAD

**Issue by myrnazhou** [cefsharp/CefSharp#758]
There is a problem when we put ```cefsharp``` wpf control inside a ```listbox```. It makes some keyboard shortcut such as ```ctrl+a``` not working. 
I've pushed it here https://github.com/Bodekaer/CefSharp/tree/CefSharpInsideListBoxTest
Is there a workaround to fix this?

**Comment by myrnazhou** [comment]
And to add more, performance when typing is noticeably slower.

**Comment by jankurianski** [comment]
Perhaps some shortcuts such as CTRL+A are handled by the listbox to select all items in a list?

Have you tried to put more items in the listbox and see if they get selected when you press CTRL+A?

Here is where you could start debugging to see whether the keyboard events are being captured by the WPF control : https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L605-L630

**Comment by amaitland** [comment]
If you put a break point at https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L894 in `OnPreviewKey` and another at https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L620 in the `SourceHook`, you'll find out if `WPF` is handling the key combination.

`OnPreviewKey` will be first, and then the `SourceHook`, if only `OnPreviewKey` is fired then the event was handled elsewhere.

> And to add more, performance when typing is noticeably slower.

Noticeably slower when compared to???

**Comment by myrnazhou** [comment]
@amaitland
when typing between the cefsharp that is inside listbox, and the other which is not.

**Comment by amaitland** [comment]
> when typing between the cefsharp that is inside listbox, and the other which is not.

At a guess if that's the case then it's likely that a total rewrite would be required, one that doesn't rely on a `SourceHook`.

Let us know how the debugging goes :+1:

**Comment by amaitland** [comment]
@myrnazhou Any further feedback on this one?

**Comment by rassilon** [comment]
I haven't tried this, but does CEF send data back out for unhandled events through KeyboardHandler for OSR like we're using in WPF?

If it does, then that might be part of the solution. (I don't recall much about WPF keyboard event propigation.)

Additionally, it seems kind of odd to make the ListBoxItem be the WPF ChromiumWebBrowser. I would think you would rather write a wrapping WPF control that contains the ChromiumWebBrowser for the entire ListBox ControlTemplate. (or whatever the WPF term is, I haven't done a lot of WPF development at all.) That'd be a much better way of leveraging the amount of effort involved in starting up CEF. 

(Especially,since the default list box style is to display more than one ListBoxItem at a time, IIRC.)

Bill

**Comment by myrnazhou** [comment]
Sorry for replying so late,
So yes, apparently the Ctrl+A is not handled there, and if I added this condition to the ```OnPreview```, it solves the issue
```(e.Key == Key.A && Keyboard.Modifiers == ModifierKeys.Control)```

**Comment by amaitland** [comment]
Excellent. Anything else before closing this?

**Comment by myrnazhou** [comment]
Should I make a PR?

**Comment by amaitland** [comment]
Yep, can you also include a comment as to the reason for the extra check?

**Comment by amaitland** [comment]
Closing as #883 has been merged.
