### ISSUE TITLE
Enable Device Mode Mobile Emulation with coding?

### ISSUE THREAD

**Issue by mirror222** [cefsharp/CefSharp#765]
Is it possible to specify the Device mode while create a new ChromiumWebBrowser object?

Thank you.

**Comment by jornh** [comment]
This: https://developer.chrome.com/devtools/docs/device-mode? 

If there is a command line switch for Chrome ... which 5 min googling told there apparently isn't https://groups.google.com/forum/#!topic/google-chrome-developer-tools/mKDeMepwdgE then it would be possible. 

So currently not supported. But you are welcome to dig upstreams - like looking at the issue pointed to in the above google-chrome-developer-tools forum post.

As i dont think it's CefSharp related (but needs upstream resolution) I think we should close the issue here. Agree?

**Comment by mirror222** [comment]
Thank you. Closed it.
