### ISSUE TITLE
OnBeforeBrowse called when there is youtube embedded

### ISSUE THREAD

**Issue by myrnazhou** [cefsharp/CefSharp#829]
Hi Guys,
I'm using ```cefsharp``` for ```WPF```. When I load page with youtube embedded player like this https://mailbird.zendesk.com/entries/21996695-Accounts-and-Identities, the ```OnBeforeBrowse``` method is always called, but the ```TransitionType``` is always ```LinkedClicked```, so I'm not sure how to differentiate with the real click. Do you know how to resolve this?
Thanks

**Comment by amaitland** [comment]
I'd be asking this `upstream` in the `cefforum`

**Comment by jornh** [comment]
Is there an `(i)frame` involved in this YouTube embedding? Then I guess exposing info from the CEF `frame` parameter in [`OnBeforeBrowse`](https://github.com/cefsharp/CefSharp/blob/0f23b663a28463a6807eeb4b8f6cec41588fa85f/CefSharp.Core/Internals/ClientAdapter.cpp#L240) in the CefSharp handler would help.

Maybe by implementing something like in [`OnFrameLoadEnd`](https://github.com/cefsharp/CefSharp/blob/0f23b663a28463a6807eeb4b8f6cec41588fa85f/CefSharp.Core/Internals/ClientAdapter.cpp#L218) or the full frame object depending on the use cases.

I say use *cases* in plural because of http://stackoverflow.com/questions/28587421/how-to-detect-clicked-links-in-cefsharp-3

**Comment by myrnazhou** [comment]
@jornh yes, there is ```iframe``` involved.

**Comment by amaitland** [comment]
>  ///
  // Source is a link click or the JavaScript window.open function. This is
  // also the default value for requests like sub-resource loads that are not
  // navigations.
  ///
  TT_LINK = 0,

https://github.com/cefsharp/CefSharp/blob/master/CefSharp/TransitionType.cs#L14

So the behavior your seeing is expected. Perhaps when the user navigates youtube will be loaded as the main frame? Have to add `isMainFrame` to `OnBeforeBrowse`.

**Comment by jornh** [comment]
@myrnazhou got any input on this? If you think the solution outlined in https://github.com/cefsharp/CefSharp/issues/829#issuecomment-75371933 would fix it for you maybe you are up to the (small) challenge of submitting a PR?

**Comment by amaitland** [comment]
If were changing the API I'd like this resolved before the upcoming release.

**Comment by rassilon** [comment]
Has anybody made a pass through and figured out where it might make sense to expose frames all over the API? I know the V8 context for callbacks involves frames so that's something think on too.

Bill

**Comment by amaitland** [comment]
> I know the V8 context for callbacks involves frames so that's something think on too.

`CefV8Context` can only be accessed in the render process, so that side of things will likely be abstracted from the user.

There was talk long about about creating a frame wrapper. I think overall there's quite a lot of work required to re-engineer the whole `API` as it hides key parts of `CEF`. Personally I don't have that much time available to commit to the project.

Short term I'd probably expose `isMainFrame` in a few additional places.

**Comment by amaitland** [comment]
@myrnazhou Did you come up with a solution to your problem?

**Comment by myrnazhou** [comment]
@amaitland 
I'm planning to do it around this week. 

@jornh 
Yes I think yous solution could work. I'll let you know how it goes.

**Comment by amaitland** [comment]
@myrnazhou Thanks. Just trying to work out some rough scheduling for the `39` release. Will you guys ever update to the official `nuget` packages?

**Comment by myrnazhou** [comment]
@amaitland 
At this moment we're still building our own ```nuget``` packages, but maybe in future. @Bodekaer

**Comment by amaitland** [comment]
Merged #889

**Comment by Bodekaer** [comment]
Nugets: I don't think we have access to release the updates.
Also, I think I'd have to review our fork, as I think there are a few things we've added which are not in the master, so we're all good with the current setup, where we use Mailbird-specific Nugets.

**Comment by amaitland** [comment]
@Bodekaer No probs.
