### ISSUE TITLE
set user-agent

### ISSUE THREAD

**Issue by pipiscrew** [cefsharp/CefSharp#844]
how I can change browser 'user agent' ??

**Comment by jankurianski** [comment]
You should do this when initializing CefSharp, like in the following file: https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/CefExample.cs

`settings.UserAgent = "My Awesome Browser";`

You need to make sure you call `Cef.Initialize` before any `ChromiumWebBrowser` instances are created (otherwise the settings are ignored).  The best place to do this is in your `Program.cs` file.

**Comment by amaitland** [comment]
Should probably add a commented out `UserAgent` example (that file is fast getting a lot of commented out code! lol)

**Comment by amaitland** [comment]
@pipiscrew Also no need to inlcude `[q`] in your issue title. We'll add the `question` label which is better for searching and sorting.

**Comment by jornh** [comment]
@pipiscrew anything else needed before close?

**Comment by pipiscrew** [comment]
no, thank you!
