### ISSUE TITLE
Feature Request - Ability to open Popup with parent browser set

### ISSUE THREAD

**Issue by Bodekaer** [cefsharp/CefSharp#869]
Hey,

How can we create custom popups?

I found out, that we can overwrite the `ILifeSpan.OnBeforePopup()`, and create our own browser instance. 
But the issue we have atm. is that we don't know how to tell the new CEF instance, who the parent browser is.

Do you know how to do this?

(e.g. it's important for a Facebook or Google login popup, where it needs to tell the parent browser, that the login was successful via Javascript).

**Comment by amaitland** [comment]
Perhaps setting the parent property of the `CefWindowInfo`?

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefWindowInfo..parent.html

**Comment by amaitland** [comment]
`SetAsPopup` is probably the go.
http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefWindowInfo.html#SetAsPopup%28cef_window_handle_t,constCefString&%29

**Comment by Bodekaer** [comment]
Yeah, that's it! 
Great thanks.

FYI @Antonyo, we just need to add support for this in CEF when we have time. 
Should be fairly straightforward.

**Comment by Antonyo** [comment]
Hi, I think what @Bodekaer meant was to set the parent popup to an existing ChromiumWebBrowser so in our `ILifeSpan.OnBeforePopup()` we can stop the creation of CEF popup and create our own window with a browser embedded simulating a popup. 
What we want to achieve is to set the parent of this embedded browser so the popup can reference it's parent browser.

As far as I know the cef.sdk does not provide a way to set the parent to an already created browser, without that option I tried to create a new method `ManagedCefBrowserAdapter.CreateOffscreenBrowser(IntPtr windowHandle, BrowserSettings^ browserSettings, String^ address)` which uses the `CefWindowInfo.setAsPopup` method but why exactly is the method `ChromiumWebBrowser.CreateOffscreenBrowser`being called for? I tried to called my method instead of it when I want to create a popup browser but still the popbrowser can't reference the parent.

**Comment by amaitland** [comment]
> As far as I know the cef.sdk does not provide a way to set the parent to an already created browser, without that option I tried to create a new method

It makes sense to specify the parent on creation. I wouldn't expect to specify a parent for an existing instance.

> why exactly is the method ChromiumWebBrowser.CreateOffscreenBrowser being called for?

You'll have to clarify, I'm unsure what your asking.

**Comment by amaitland** [comment]
As you don't need a true popup, just need to pass in the parent, you can probably just call `CreateOffscreenBrowser` and pass in the handle from the parent.

My suggestions would be to
- Pass in the handle to `OnBeforePopup` as a param
- When you create a new instance of `ChromiumWebBrowser` pass in the handle and instead of calling `source.Handle`, use your parent handle instead (only when creating as a `popup`)

Hopefully that's enough.

(`SetAsPopup()` and `SetAsWindowless()` are merely helper methods that set values in different scenarios, I'd suggest looking in `cef_win.h` to get a better understanding of what's going on.)

**Comment by Antonyo** [comment]
Thanks @amaitland, I've already tried that,  in my previous message I meant to say that I created a method `ManagedCefBrowserAdapter.CreatePopupBrowser(IntPtr parentWindowHandle, BrowserSettings^ browserSettings, String^ address, String^ title)` and called instead of `CreateOffscreenBrowser` in popup scenario and it didn't work. 

My question was what's the difference of creating an offscreen browser instead of a normal one?  Maybe I'm a bit confused about the name of the method so I didn't know if it was safe not to call `CreateOffscreenBrowser` method.

**Comment by amaitland** [comment]
`CreateOffscreenBrowser` creates the browser used with `WPF`, the normal one is used by `WinForms`.

It's entirely possible you can't pass in the parent when using `SetAsWindowless`.

**Comment by amaitland** [comment]
> and called instead of CreateOffscreenBrowser in popup scenario and it didn't work.

What exactly happened?

**Comment by amaitland** [comment]
Also can you push what you've tried to `GitHub` somewhere so I can see, make this go a lot quicker, rather than guessing what's going on.

**Comment by Antonyo** [comment]
Sorry for the delay, I commit the code in here:
https://github.com/Antonyo/CefSharp/commit/05972b5e337385400710be7bd8d65758b6c94603
If you run the Wpf example a browser loaded with `https://calendar.sunrise.am/` will appear, click on the `Connect with Google` button a window simulating a popup will appear with a google oauth page but a javascript error appears:

`Cannot read property 'closed' of undefined` 

and nothing happens when you click on any of the buttons of the popup, as it cannot communicate with it's parent browser.

Thanks

**Comment by amaitland** [comment]
@Antonyo Your branch doesn't build. I've commented inline.

I think it's worth asking on `ceforum` to clarify that it's actually possible.

**Comment by Antonyo** [comment]
@amaitland sorry about that, you're right, I noted your comments. It's not production code or anything, I just wrote the changes quickly for you to see and didn't have the chance to test it. I'll pass the question on `ceforum`.

**Comment by jamespearce2006** [comment]
Just wondering if anyone has got anywhere with this for WPF apps?

I was wondering whether calling SetAsPopup before calling SetAsWindowless might work (so that the window frame name gets set), but it doesn't appear to.

**Comment by jamespearce2006** [comment]
There's a discussion on CefForum here:

http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=11569&hilit=offscreen+popup

It looks like CefSharp needs to process OnBeforePopup to call SetAsWindowless on windowInfo - perhaps create a new ChromiumWebBrowser instance and pass that back to the client app to deal with as appropriate...

**Comment by amaitland** [comment]
> http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=11569&hilit=offscreen+popup

Nice find :+1: 

> CefSharp needs to process OnBeforePopup to call SetAsWindowless

Only in the context of the `WPF/OffScreen` versions, will need to skip that part for `WinForms`. Overall the concept is pretty simple, finding an elegant way to get the `ClientAdapter` from a new `ChromiumWebBrowser` instance will be the fiddly part.

Any changes need to be based on the `2272` branch.

**Comment by jamespearce2006** [comment]
> Only in the context of the WPF/OffScreen versions

Yes. Sorry - my app is WPF. When all you've got is a hammer...

**Comment by jamespearce2006** [comment]
Is 2272 a future development branch?

**Comment by jamespearce2006** [comment]
Could we add a method to access the ClientAdapter on the IWebBrowserInternal interface?

    ClientAdapter^ GetClientAdapter();

(I'm not used to managed C++)
Alternatively, a centralized IWebBrowser->ClientAdapter map?

Additionally, will it need a breaking change to ILifeSpanHandler.OnBeforePopup, to allow the client to indicate that it wants an offscreen popup, and to provide the IWebBrowser instance it wants to use?

**Comment by amaitland** [comment]
> Is 2272 a future development branch?

Correct. That's the next version, based on Chromium `41`

> Could we add a method to access the ClientAdapter on the IWebBrowserInternal interface?

`ClientAdapter` is an unmanaged class, so can't reference it directly in `C#`, also `IWebBrowserInternal` is in the top level library. Will need to implement an interface in `CefSharp.Core` that has a a param of `CefRefPtr<CefClient>`. `ManagedCefBrowserAdapter` has an `offScreenRendering` param that will likely be passed into the `ClientAdapter`.

It'll probably start out being a little messy, need 2-3 passes to cleanup the code. So if you do have a go at this, once you get something basic working you can create a `PR`, then we can look at ways to improve.


> Additionally, will it need a breaking change to ILifeSpanHandler.OnBeforePopup, to allow the client to indicate that it wants an offscreen popup, and to provide the IWebBrowser instance it wants to use?

Most likely, I wouldn't worry about that as a whole. There are many breaking changes in `2272` as large parts of the `CEF API` that were previously inaccessible are exposed.

**Comment by Antonyo** [comment]
@jamespearce2006 I tried several methods and none of them worked, I still need to find a solution. Thanks for the link to that discussion. In theory should be supported, for instance here:

http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=10287

you can see an example of reparenting the browser but it didn't work for me.

**Comment by jamespearce2006** [comment]
@amaitland I can't seem to get the 2272 branch to build. I get lots of nuget errors. Is there a trick to it?

@Antonyo I think the browser needs to be created in response to an OnBeforePopup, not re parented after the fact.

**Comment by amaitland** [comment]
> @amaitland I can't seem to get the 2272 branch to build. I get lots of nuget errors. Is there a trick to it?

Latest build is working see https://ci.appveyor.com/project/cefsharp/cefsharp/build/41.0.0-CI1043

Is `nuget` downloading the packages?

**Comment by jamespearce2006** [comment]
Never mind - I just tried it again and it worked.

**Comment by jamespearce2006** [comment]
I'm not getting very far with this. I've modified ClientAdapter to look like this:

        bool ClientAdapter::OnBeforePopup(CefRefPtr<CefBrowser> browser, CefRefPtr<CefFrame> frame, const CefString& target_url,
            const CefString& target_frame_name, const CefPopupFeatures& popupFeatures, CefWindowInfo& windowInfo,
            CefRefPtr<CefClient>& client, CefBrowserSettings& settings, bool* no_javascript_access)
        {
            ILifeSpanHandler^ handler = _browserControl->LifeSpanHandler;
			IWebBrowser^ newBrowser = nullptr;

            if (handler == nullptr)
            {
                return false;
            }

            bool returnVal = handler->OnBeforePopup(_browserControl, gcnew CefFrameWrapper(frame, _browserControl->BrowserAdapter), StringUtils::ToClr(target_url),
                windowInfo.x, windowInfo.y, windowInfo.width, windowInfo.height, newBrowser);

			IWebBrowserInternal^ newBrowserInternal = dynamic_cast<IWebBrowserInternal^>(newBrowser);

			if (newBrowserInternal != nullptr)
			{

				IRenderWebBrowser^ renderBrowser = dynamic_cast<IRenderWebBrowser^>(newBrowser);
				if (renderBrowser != nullptr)
				{
					windowInfo.SetAsWindowless(windowInfo.parent_window, TRUE);
				}

				ManagedCefBrowserAdapter^ browserAdapter = dynamic_cast<ManagedCefBrowserAdapter^>(newBrowserInternal->BrowserAdapter);
				if (browserAdapter != nullptr)
				{
					client = browserAdapter->GetClientAdapter().get();
				}

			}

			return returnVal;
        }

I've got my client returning a new ChromiumWebBrowser in the OnBeforePopup call (it gets assigned to new Browser).
I can verify that a JS call to window.open() actually returns a value, but if I modify the returned value's document, nothing happens - my ChromiumWebBrowser remains blank. It seems to me like something's not getting "joined up".

Any ideas?

**Comment by jamespearce2006** [comment]
OK, I have this working. The code is rather rough. I'll clean it up, then submit a PR as a talking point. The main area of complexity is getting this working with the MVVM pattern.

**Comment by amaitland** [comment]
Closing with #1150
