### ISSUE TITLE
Offscreen Rendering of PDF's Fails

### ISSUE THREAD

**Issue by tbowers** [cefsharp/CefSharp#874]
#### Issue Summary
When Chromium loads a PDF, it displays it using it's built in reader. When the same PDF is used with the off screen browser, I would expect the resulting image to contain a picture of PDF. However, the resulting image is black.

#### Steps to Reproduce
1. Open up CefSharp.OffScreen.Example app
2. Replace             
`const string testUrl = "http://www.google.com";`
with
`const string testUrl = "http://www.irs.gov/pub/irs-prior/f1040ez--2014.pdf";`
3. Run app, note resulting image is blank

#### Technical details
* CefSharp Version: tag v39.0.0-pre03
* Operating System: Windows 7
* x86
* OffScreen:

**Comment by jankurianski** [comment]
The problem is that Chrome is sending a blank screen of the PDF viewer, and the example app is designed to display the first frame and exit.  You will need a delay.

In the example `Program.cs`, change the following line:

`browser.ScreenshotAsync().ContinueWith(DisplayBitmap);`

to:

`Task.Delay(5000).ContinueWith(t => browser.ScreenshotAsync().ContinueWith(DisplayBitmap));`

And you will get a screenshot of the PDF viewer.  Albeit with some of the user interface showing.

**Comment by amaitland** [comment]
@tbowers Anything further before closing this?

**Comment by tbowers** [comment]
I apologize for the late reply. That seemed to work and the explanation makes sense. Thank you very much.
