### ISSUE TITLE
Catch errors from libcef.dll

### ISSUE THREAD

**Issue by DominikPalo** [cefsharp/CefSharp#944]
Hi,

I have WPF application which uses CEFsharp. But sometimes my app on client machines unexpectedly crashes and I can't get details why (on my developer machine it never crashed). But, after examing Windows event logger, I found this: 

```Description:
Faulting application name: SlidesDrive.exe, version: 0.16.1.0, time stamp: 0x5527e0eb
Faulting module name: libcef.dll, version: 3.2171.1979.0, time stamp: 0x54c0967c
Exception code: 0x4000001f
Fault offset: 0x0013b2d0
Faulting process id: 0x1eb4
Faulting application start time: 0x01d073ad1df1edc5
```

So, problem is in libcef.dll, but I can't get more informations about problem. How can I get more details about this error or catch libcef.dll exceptions directly in app to avoid crash of entire app?

**Comment by amaitland** [comment]
Does your `debug.log` provide any clues? Maybe up the logging level as well.

Also `3.2171.1979` is outdated, I'd suggest upgrading to the official `39.0.0` release.

There is no easy way to catch exceptions from the `unmanaged` side of things. You can potentially get a debug build of `libcef.dll`, which may provide a more detailed exception. If you download the relevant build from https://cefbuilds.com/#branch_2171 you'll see there's a debug version. (It will be a few hundred mb in size, so they're too big to package and redistribute normally).

**Comment by DominikPalo** [comment]
Thanks,

but I can't use cef debug.log on clients, because my app needs to be installed into Program Files (and in this case app needs admin privileges to allow writting files to the Program Files, which clients dont have). Maybe changing location of debug.log file to AppData folder will help - it is possible to change debug.log location?

And I also updated to 39.0.0, I hope it improves stability :)

**Comment by amaitland** [comment]
> it is possible to change debug.log location?

Yes see https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/CefSettings.h#L88

**Comment by rassilon** [comment]
>  Exception code: 0x4000001f

This (via google) is the exception code that occurs when the `int 3` instruction is executed.

`CEF` is known to do this when you violate its threading restrictions about what executes on which `CEF` thread. See [CEF Threads](https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage.md#markdown-header-threads) for the list of `CEF` threads.

Your user can utilize [Procdump](https://technet.microsoft.com/en-us/sysinternals/dd996900.aspx) like this:

    procdump -e -ma <binaryname or PID>  <dumpfile.dmp> 

If your user is on Win 8.1 or later they can use the `-r` option for a bit more efficiency in creating the memory dump.

If that command line doesn't do the trick, you might need to use `procdump`'s `-e1` option instead of `-e`. 

You then load the memory dump into Visual Studio or WinDbg and see what the call stack for the `CEF` issue is. (You can google about how to deal with memory dumps and .Net if you haven't done it before.) My recommendation is to use Visual Studio 2013 with integrated WinDbg, or WinDbg.

Bill

**Comment by amaitland** [comment]
@DominikPalo Any further update on this?

**Comment by amaitland** [comment]
Closing due to lack of feedback.
