### ISSUE TITLE
Multiple CefSharp.BrowserSubprocess.exe

### ISSUE THREAD

**Issue by rstmm** [cefsharp/CefSharp#968]
Hi,

we use CefSharp around a Sencha JS application and are having problems with memory leaks we're trying to fix at the moment.
What we don't understand: When we start our application, we get 3 "CefSharp.BrowserSubprocess.exe" Processes running.

I identified 1 of these as the developer console, which we are also launching. 
But I don't understand how the other 2 play together. We only create one ChromiumWebBrowser object and load 1 URL.

Is there any way to find out what which process is doing?

Thanks in advance!

**Comment by amaitland** [comment]
Look at the command line arguments (e.g. in `Task Manager`), you should have one for `gpu-process` and a minimum of one `renderer` processes for each instance of `ChromiumWebBrowser`

So if you've got one for `DevTools`, then three is expected.

What sort of numbers are you seeing? What version are you using? What flavor? e.g. `WPF`, `WinForms`?

**Comment by amaitland** [comment]
See `Architectural Interlude: The GPU Process`
https://www.chromium.org/developers/design-documents/gpu-accelerated-compositing-in-chrome

**Comment by amaitland** [comment]
Remembering that `CefSharp` is just a wrapper around `CEF` it might be worth coming the `cefclient` example to see how it performs. This will help identify if the issue is `CefSharp` specific.

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

You can use `Chrome` to take a heap snapshot to see where memory usage is going.

- Enable remote debugging on port xxxx
- Open Chrome (it does have to be chrome), and point it at localhost:xxxx
- You should see a single link, should have your app name and computer name in it. Click it.
- Click 'Profiles' at the top, then 'Take Heap Snapshot' and 'Take Snapshot' 

May provide you with some info.

**Comment by amaitland** [comment]
@rstmm Anything further on this?

**Comment by rstmm** [comment]
Oh sorry, forgot to answer this one... :/

Thanks for the explanation, the 3 processes are clear now and we found our memory leak, thanks to the chrome developer console and some guessing :)

Since the issue is resolved and the processes are clear now, I'm closing it.

Thanks again!
